### ISSUE TITLE
Figure out what's wrong with rows 8403-8812

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#100]
When importing the February data, we see a few hundred errors of the form:
```
Problem with row 8403: Not a date: Active
```

It's likely that the data is shifted over a column, but we need to resolve.

**Comment by tadhg-ohiggins** [comment]
I'm not sure whether data's been shifted or if `policySunset` is being set to “Active” here because there's no sunset date.

Also, <https://github.com/18F/omb-eregs/pull/111> won't fix this because in all of these rows I've looked at, both `policySunset` and `reqStatus` are non-date values.

**Comment by Thomas-Romanoff** [comment]
seems to be fixed
