### ISSUE TITLE
As a policy analyst or contractor, I need to be able to un-publish a document that has been completed

### ISSUE THREAD

**Issue by austinhernandez** [18F/omb-eregs#1001]
## assumptions 
- [x] The policy is live on the site and viewable by the general public. A contractor or analyst must remove it to make changes or because it is incorrect.

## actions 
- [x] Create wireframes high or low fidelity and/or a task flow for how a user will go about un-publishing a document.
- [ ] Document necessary warning messages and or error messages
- [ ] Decide on what the unpublished page looks like on the front-end policy library view
- [ ] Display the status of the document (editable or not) so that a user knows if the un-publishing was successful or if they are looking at a currently un-published or published document. 
- [ ] Validate flow(s) with teams

## Suggestions, things to consider, notes, etc.
- Related to #849 
- Consider a dropdown that shows un-publish (keep it simple, no extra things)
- Try to figure out how to incorporate the "status" of a policy (e.g. published, in review, unpublished etc.). This could be a button, dropdown or text, letting a user know if un-publish has been successful.
- Consider a [timeless gif indicating a page is under under construction](http://bestanimations.com/Site/Construction/under-construction-gif-6.gif)
- [Most recent Sketch document is here on Google Drive](https://drive.google.com/open?id=1yf9ZVDOtE9RMIQf2ybC5JRW9t9S5d7a8)
- Component library is shared.

**Comment by rtwell** [comment]
after much deliberation, the new unpublish flow is simlply this:
![image](https://user-images.githubusercontent.com/12564977/36054449-1bdfc892-0dbc-11e8-83b8-16f5a6031ac0.png)

**for MVP** no metadata or placeholder is available, the policy is either visible, or not. Correct me if im wrong @austinhernandez @thebestsophist @cmc333333

**Comment by rtwell** [comment]
@austinhernandez will be incorporating this into the full user flow in #1008
