### ISSUE TITLE
As a policy analyst or contractor, I need to be able to identify preamble and metadata content in my document 

### ISSUE THREAD

**Issue by austinhernandez** [18F/omb-eregs#1010]
## assumptions 
- [ ] The user has uploaded a new document or is editing an existing one and must identify areas in the text where there is preamble and meta data content.

## actions 
- [ ] Create wireframes high or low fidelity and/or a task flow for how a user will select and identify preamble and metadata text in the WYSIWYG editor
- [ ] Document necessary warning messages and or error messages
- [ ] Make sure all paragraph and text styles are accounted for in the mockups
- [ ] Metadata and preamble text is finalized and accounted for in the mockups
- [ ] Validate interaction(s) with teams

## Suggestions, things to consider, notes, etc.
- [Most recent Sketch document is here on Google Drive](https://drive.google.com/open?id=1yf9ZVDOtE9RMIQf2ybC5JRW9t9S5d7a8)
- Component library is shared.
- I was using the [scrivener](https://www.literatureandlatte.com/scrivener/overview), Google docs, and Microsoft word as foundations for interaction patterns.

## Current mockups

![image](https://user-images.githubusercontent.com/23194720/36111135-1b433f8e-0ff3-11e8-8e31-d0688b2aa594.png)

![wysiwyg interactions](https://user-images.githubusercontent.com/12564977/36123401-18bd8d36-1012-11e8-979b-555b2891f654.png)

**Comment by austinhernandez** [comment]
tbd in later sprint, design styles for preamble and meta data

**Comment by rtwell** [comment]
![preamble 1](https://user-images.githubusercontent.com/12564977/36283316-c2ccd35a-1269-11e8-9a54-6b2f4fae50b3.png)
![preamble 2](https://user-images.githubusercontent.com/12564977/36283317-c2e6c1c0-1269-11e8-9342-36a3b0d5c076.png)
![preamble 3](https://user-images.githubusercontent.com/12564977/36283318-c304553c-1269-11e8-98d9-0b2a7ca7b5fe.png)
![preamble 4](https://user-images.githubusercontent.com/12564977/36283319-c3316d60-1269-11e8-916e-cb9dd34252e1.png)
![preamble 5](https://user-images.githubusercontent.com/12564977/36283320-c352b1e6-1269-11e8-8dea-4582a664dc84.png)

**Comment by rtwell** [comment]
## the issuance date will need to be validated in two ways:

### trigger 1: document save
you cannot save a policy without having a valid date assigned. So, on click for **save** will trigger the error _in the preamble area_
### trigger 2: inline validation
when a user highlights a date, and selects` Issuance date`, the highlighted text is now colorized and marked with **Issuance date:**. If the Issuance date is modified by the user in a way that _invalidates_ the date, the `Issuance date` changes into an inline error message so the user can correct the error.
