### ISSUE TITLE
Figure out what's wrong with requirements 1315.01–1315.26

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#103]
These all have `X` in the `Other` field, which should be populated with a list of comma-separated keywords.

Presumably the columns have been inadvertently shifted over, and they're not supposed to have keyword of `X`, but we need to confirm this and get a corrected version.

I've asked about this in Slack.

**Comment by tadhg-ohiggins** [comment]
The requirements in question all derive from final guidance on implementing the Plain Writing Act of 2010, found in this memo: <https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2011/m11-15.pdf>.

All the data in the columns for these requirements seems to be in the right place except for the keywords columns.

The data suggests that the categories for these requirements are:

- Customer Services (which seems to make sense)
- Definitions (which seems to make sense)
- “X” as a category in “Other”, which seems clearly wrong. The memo includes requirements for compliance reports, so the most likely explanation is that the last “X” should be moved left one column.

**Comment by Thomas-Romanoff** [comment]
Fixed
