### ISSUE TITLE
allow admin users to edit link to original policy

### ISSUE THREAD

**Issue by doc-mcconnell** [18F/omb-eregs#1055]
Currently, there is no way to correct a broken "See original" link to the pdf version of a published policy. For example, clicking "See original" on M-16-21 results in a 404 error. Admin users should be able to edit this, either from the Change Policy page in the admin interface, or from the XML editor. Thanks!

**Comment by cmc333333** [comment]
Hey there, @doc-mcconnell , I think that'd only require adding `'uri'` to [this list](https://github.com/18F/omb-eregs/blob/ba39d4872fd4658959cf886e5aa15db39e97b437/api/reqs/admin.py#L20) in the admin. Want to take a shot and test it out?

**Comment by doc-mcconnell** [comment]
Submitted -- https://github.com/18F/omb-eregs/pull/1056

Thanks!

**Comment by cmc333333** [comment]
Merged! It's now deployed to demo; please give it a go there and if it's all good, we can make a PR to prod.

**Comment by doc-mcconnell** [comment]
I don't think I have access to the admin interface on the demo site. Is this the right URL? 
https://omb-eregs-api-demo.app.cloud.gov/admin/

**Comment by cmc333333** [comment]
Indeed! I'll defer to @krues8dr to get you permission to avoid stepping on any policy process toes

**Comment by doc-mcconnell** [comment]
@cmc333333 -- tested the change in demo, looks good to me!

**Comment by cmc333333** [comment]
Excellent. Pushed to prod! Please re-open if something looks amiss.
