### ISSUE TITLE
High level visual design

### ISSUE THREAD

**Issue by micahtaylor** [18F/omb-eregs#113]
First pass at throwing something against the wall to begin to discuss how the visual design will begin. 
Discussion encouraged on Invision for now.
https://gsa.invisionapp.com/share/M6AU3YB49#/223308335_Start_Styled

**Comment by micahtaylor** [comment]
Some discussion happening on Slack 
https://gsa-tts.slack.com/archives/eregs-omb/p1489518896976607

**Comment by micahtaylor** [comment]
0.2 visual pass 
https://gsa.invisionapp.com/share/M6AU3YB49#/screens/223777085

**Comment by yowill** [comment]
CLOSED!
