### ISSUE TITLE
Figure out what to do about requirements without IDs

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#115]
[Updated to refer to 2017-03-21 data.]

Probably-active requirements without requirement IDs:

- [ ] Rows791–792/Policy 39, Guidance on Inter-Agency Sharing of Personal Data - Protecting Personal Privacy: “NA”.
- [ ] Rows 793–794/Policy 40, Reducing Cost and Improving Quality in Federal Purchases of Commercial Software: “NA”. (But the last row for policy 40 has a requirement ID of `40.03`.)
- [ ] Row 935/Policy 48, SmartBUY Agreement with Oracle: “None”.
- [ ] Row 1080/Policy 67, Immediate Review of Information Technology Products: “None”.
- [ ] Row 1418/Policy 88, Ensuring the Accessibility of Federal Electronic and Information Technologies Procured by Federal Agencies: “None”.
- [ ] Row 1473/Policy 92, Open Government Plan: “None”.
- [ ] Row 1474/Policy 96, Release of the Planning Guide/Roadmap toward IPv6 Adoption within the US Government: “None”.
- [ ] Row 3571/Policy 1064, Improving Statistical Activities through Interagency Collaboration: “N/A”.

Rescinded/duplicate requirements without requirement IDs:

- [ ] Row 6224/Policy 1327, M-01-05 - Guidance on Inter-Agency Sharing of Personal Data - Protecting Personal Privacy: “NA”.
- [ ] Row 6225/Policy 1328, M-03-14 - Reducing Cost and Improving Quality in Federal Purchases of Commercial Software: “NA”.
- [ ] Row 6226/Policy 1329, M-04-04 - E-Authentication Guidance for Federal Agencies: “NA”.

The key question for OMB is:

- Do these requirements actually lack IDs or is this a data issue?

Some relevant development-side questions are:

- Can we support requirements that don't have IDs? (I *think* the answer is “no”.)
- If they lack IDs, how do we handle synthesizing IDs for them?
- Are any of these answers different for rescinded requirements?

We can check off the requirements here as we get info about how to handle them.

**Comment by Thomas-Romanoff** [comment]
Fixed
