### ISSUE TITLE
Start prototyping or sketching after week 1

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#12]
After first round of interviews, start initial sketching to get some reactions to early ideas and prototypes so that we can get early feedback and start honing the mvp.

**Comment by cmc333333** [comment]
Didn't do this until Thursday, but we've got our sketches: https://app.mural.ly/t/gsa6/m/gsa6/1485966863763

**Comment by cmc333333** [comment]
Reopening so that @donjo can add a publicly visible link

**Comment by donjo** [comment]
https://app.mural.ly/t/gsa6/m/gsa6/1485966863763/view/571003727
