### ISSUE TITLE
Look at Django modules for versioning

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#125]
For example http://django-simple-history.readthedocs.io/en/latest/ or http://django-reversion.readthedocs.io/en/stable/

**Comment by cmc333333** [comment]
My vote'd be for revisions -- I have a vague recollection of it being the
most standard tool for that.

**Comment by tadhg-ohiggins** [comment]
`django-reversion` is now in place in the admin UI.
