### ISSUE TITLE
Celebrate Tadhg's birthday!

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#14]

**Comment by jehlers** [comment]
![birthday-dog](https://cloud.githubusercontent.com/assets/4267825/22217318/7f4085c6-e170-11e6-992d-9593ea92ce4a.gif)

**Comment by donjo** [comment]
🎉 🎈 🎂 🎈 🎉

**Comment by tadhg-ohiggins** [comment]
Hahaha, I just saw this, thank you all!

**Comment by yowill** [comment]
Mission accomplished.
