### ISSUE TITLE
What do we do about the requirement ID numbering for 1323?

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#141]
Starting at row 6089, there are over 100 requirements for policy number 1323. The Excel issues with decimals here appear to mean that we have the following:

- `1323.1` twice—one should be `1323.10` and another should be `1323.100`, but it's not possible for us to determine the correct answer automatically.
- `1323.11` twice—one should be `1323.11` and another should be `1323.110`, just like the previous item.

The ordering in the latest data file isn't numeric by requirement ID, so `1323.1` is present in consecutive rows, and `1323.11` is later present in two consecutive rows, which is one of the reasons why we can't automatically determine the correct IDs.

**Comment by Thomas-Romanoff** [comment]
Fixed
