### ISSUE TITLE
What do we do about the duplication of requirement IDs starting with `1345`?

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#142]
Rows 6511–6531 have requirements 1345.01–1345–22 (although there is no `1345.21`), and rows 6532–6552 have requirements with exactly the same requirement IDs. The latter rows have `Out of Date` as their status.

Should out of date or rescinded requirements have the same ID as current ones? If so, how do we handle that? If not, what should their IDs be?

**Comment by Thomas-Romanoff** [comment]
fixed
