### ISSUE TITLE
What do we do about duplicate requirement IDs in later rows for 1393.xx?

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#145]
At row 7883, the requirement IDs for policy number `1393` stop increasing and seem to start over at `1393.02` (the previous value being `1393.66`), then proceed in increments to `1393.25`. The row contents don't repeat from the earlier uses, so these aren't duplicated rows. Should these essentially have 0.65 added to them, so that they would run from `1393.67` to `1393.90`?

**Comment by tadhg-ohiggins** [comment]
In row 7815, the requirement ID is `1392.99`; in row 7816, it's `1393` even though the policy number is the same (`1392`) for both rows. All the following rows through row 7882 seem to have the wrong number (`1393`) as the first part of the requirement ID, since they're all marked as having a policy number of `1392`.

**Comment by Thomas-Romanoff** [comment]
Fixed- Turned out that the flash fill in excel messed up the req ids.  it was a bigger issue then 1392...
