### ISSUE TITLE
What do we do about requirement IDs that only contain policy numbers?

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#147]
- [ ] In row 959/policy 60,  the first requirement has a bare `60` (the next row's value is `60.01`).
- [ ] In row 1381/policy 83, the first requirement has a bare `83` (the next row's value is `83.1`).

**Comment by Thomas-Romanoff** [comment]
fixed

**Comment by tadhg-ohiggins** [comment]
These were all fixed, and the fixed data is now in production.
