### ISSUE TITLE
What do we do about non-standard date values?

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#148]
It's possible the answer is “nothing”; if the importance of the various date fields is low, and the importance of sorting/filtering by date is also low, we don't really need to fix these.

Nevertheless, the list of values that we currently can't parse in date fields is:
- `37774`
- `Active`
- `Active `
- `Effective 11/29/2000 & sunsets in two years: 11/29/2002`
- `FY2015`
- `Past Due`
- `Possible Rescission`
- `Rescinded `
- `TBA`
- `Three Years`
- `Through 2016`
- `Underlying memo M-01-08 was effective 11/29/2000 & sunsets in two years: 11/29/2002`
- `will be in effect for the calendar year 2012`

**Comment by Thomas-Romanoff** [comment]
@tadhg-ohiggins Do you want me to make changes to a CSV that I send you, or directly in the admin portal?

**Comment by Thomas-Romanoff** [comment]
@tadhg-ohiggins starch that... ill send an updated csv.

**Comment by Thomas-Romanoff** [comment]
fixed

**Comment by tadhg-ohiggins** [comment]
The listed values were fixed, and while the question of how to handle other nonstandard date values is still open, that can be addressed in another issue if necessary.
