### ISSUE TITLE
Create "no results" view

### ISSUE THREAD

**Issue by theresaanna** [18F/omb-eregs#171]
If a user selects filters that yield no requirements, we should display some kind of notice that there are no results.

**Comment by nicoleslaw** [comment]
In Slack, I was suggesting the following: 

> We could have more of an empty state message, like: `2 results found. Try removing some filters to see more results.`

**Comment by micahtaylor** [comment]
@theresaanna No results - https://gsa.invisionapp.com/share/M6AU3YB49#/237536492_Requirement_Listing_No_Results

**Comment by carodew** [comment]
This is related to #236 – we should make sure the two issues are coordinated. 

Right now the suggested text in that thread and in the mock up are different, I tend to prefer the idea of guiding the user to the possible next step with the "try removing some filters ... " language that @nicoleslaw has suggested.

**Comment by micahtaylor** [comment]
Good catch @carodew! I updated the treatment and the text to match #236.
@theresaanna Let me know if you need anything else.

**Comment by micahtaylor** [comment]
Began taking a stab at this @theresaanna.
Getting a length error on this line for obvious reasons. 😜  - https://github.com/18F/omb-eregs/blob/no-results-view/ui/components/pagers.jsx#L14
I welcome you expertise.

**Comment by cmc333333** [comment]
Did #417 resolve?

**Comment by micahtaylor** [comment]
Yes!
