### ISSUE TITLE
Go back and pull out of the logs the list of requirement ids that are clearly wrong

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#184]
- [x] Get them
- [x] Send to Tom

**Comment by tadhg-ohiggins** [comment]
The following is a table of the problematic requirement IDs.

It's not clear in which ways they're wrong, and it's likely that requirement IDs near them could also be wrong. For example, it's possible that `6.1100` should be `6.110`, `6.110` should be `6.11`, and `6.11` should be something else.

| Requirement ID Prior to correction | After correction |
| --- | --- |
| 6.110 | 6.1100 |
| 6.180 | 6.1800 |
| 6.190 | 6.1900 |
| 6.200 | 6.2000 |
| 1001.110 | 1001.1100 |
| 1001.120 | 1001.1200 |
| 1001.130 | 1001.1300 |
| 1029.1010 | 1029.10100 |
| 1029.1020 | 1029.10200 |
| 1029.1030 | 1029.10300 |
| 1029.1040 | 1029.10400 |
| 1029.1050 | 1029.10500 |
| 1029.1060 | 1029.10600 |
| 1029.1070 | 1029.10700 |
| 1029.1080 | 1029.10800 |
| 1029.1090 | 1029.10900 |
| 1029.1100 | 1029.11000 |
| 1029.1110 | 1029.11100 |
| 1029.1120 | 1029.11200 |
| 1029.1130 | 1029.11300 |
| 1029.1140 | 1029.11400 |
| 1029.1150 | 1029.11500 |
| 1029.1160 | 1029.11600 |
| 1029.1170 | 1029.11700 |
| 1029.1180 | 1029.11800 |
| 1029.1190 | 1029.11900 |
| 1029.1200 | 1029.12000 |
| 1029.1210 | 1029.12100 |
| 1029.1220 | 1029.12200 |
| 1029.1230 | 1029.12300 |
| 1029.1240 | 1029.12400 |
| 1029.130 | 1029.1300 |
| 1029.140 | 1029.1400 |
| 1029.150 | 1029.1500 |
| 1029.160 | 1029.1600 |
| 1029.170 | 1029.1700 |
| 1029.180 | 1029.1800 |
| 1029.190 | 1029.1900 |
| 1029.210 | 1029.2100 |
| 1029.220 | 1029.2200 |
| 1029.230 | 1029.2300 |
| 1029.240 | 1029.2400 |
| 1029.250 | 1029.2500 |
| 1029.260 | 1029.2600 |
| 1029.270 | 1029.2700 |
| 1029.280 | 1029.2800 |
| 1029.290 | 1029.2900 |
| 1029.310 | 1029.3100 |
| 1029.320 | 1029.3200 |
| 1029.330 | 1029.3300 |
| 1029.340 | 1029.3400 |
| 1029.350 | 1029.3500 |
| 1029.360 | 1029.3600 |
| 1029.370 | 1029.3700 |
| 1029.380 | 1029.3800 |
| 1029.390 | 1029.3900 |
| 1029.410 | 1029.4100 |
| 1029.420 | 1029.4200 |
| 1029.430 | 1029.4300 |
| 1029.440 | 1029.4400 |
| 1029.450 | 1029.4500 |
| 1029.460 | 1029.4600 |
| 1029.470 | 1029.4700 |
| 1029.480 | 1029.4800 |
| 1029.490 | 1029.4900 |
| 1029.510 | 1029.5100 |
| 1029.520 | 1029.5200 |
| 1029.530 | 1029.5300 |
| 1029.540 | 1029.5400 |
| 1029.550 | 1029.5500 |
| 1029.560 | 1029.5600 |
| 1029.830 | 1029.8300 |
| 1029.840 | 1029.8400 |
| 1029.850 | 1029.8500 |
| 1029.860 | 1029.8600 |
| 1029.870 | 1029.8700 |
| 1029.880 | 1029.8800 |
| 1029.890 | 1029.8900 |
| 1029.910 | 1029.9100 |
| 1029.920 | 1029.9200 |
| 1029.930 | 1029.9300 |
| 1029.940 | 1029.9400 |
| 1029.950 | 1029.9500 |
| 1029.960 | 1029.9600 |
| 1029.970 | 1029.9700 |
| 1029.980 | 1029.9800 |
| 1029.990 | 1029.9900 |
| 1205.110 | 1205.1100 |
| 1205.120 | 1205.1200 |
| 1205.130 | 1205.1300 |
| 1205.140 | 1205.1400 |
| 1205.150 | 1205.1500 |
| 1391.110 | 1391.1100 |
| 1391.120 | 1391.1200 |
| 1391.130 | 1391.1300 |
| 1391.140 | 1391.1400 |
| 1391.150 | 1391.1500 |
| 1391.160 | 1391.1600 |
| 1391.170 | 1391.1700 |

**Comment by tadhg-ohiggins** [comment]
Closing this as there are no more actions for this on our side.
