### ISSUE TITLE
Change “Keywords” to “Topics”

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#237]
Why: Keywords isn’t a word that effectively explains what kind of word/phrase users can search for.

**Comment by micahtaylor** [comment]
Is the desire to keep "Keywords" in the admin and just change it to "Topics" to the frontend users?

**Comment by cmc333333** [comment]
We should be consistent everywhere, so we'd swap out the term in the admin, too. I _think_ this is just a big ol search and replace + a data migration + a redirect.

**Comment by cmc333333** [comment]
@micahtaylor I'm happy to take the backend updates if you want to take the templates

**Comment by micahtaylor** [comment]
Feel free to look it over @cmc333333 
https://github.com/18F/omb-eregs/pull/255

**Comment by cmc333333** [comment]
Merged!
