### ISSUE TITLE
Implement new policy page style. 

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#240]
Why: To make the differences between the requirement view and the policy view more distinct, we are going to try a new version of the policy page that doesn’t show summaries of requirements within a policy, just the policies themselves and some important metadata, along with a count of how many requirements apply to the current set of filters.

[Please update with the latest mocks]

**Comment by theresaanna** [comment]
Assigned to @micahtaylor for mocks. @micahtaylor, please assign to me when mocks are ready! Thanks.

**Comment by micahtaylor** [comment]
@theresaanna, is this what we are calling the policy listing page?
That is found here - https://gsa.invisionapp.com/share/M6AU3YB49#/229078016_Policy_Listing
