### ISSUE TITLE
De-emphasize the OMB requirement ID in the requirement view.

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#241]
Why: The display of the internal OMB requirement IDs were causing confusion with users. Since this number doesn’t exist anywhere else we can choose to either hide it entirely or display it alongside the other pieces of metadata.

**Comment by theresaanna** [comment]
@micahtaylor is the work here to move the requirement ID underneath the requirement, with the other metadata?

**Comment by micahtaylor** [comment]
Yes! you can see it here -
 https://gsa.invisionapp.com/share/M6AU3YB49#/226629590_Start_Styled_0-3

**Comment by micahtaylor** [comment]
Moved, rearranged, pulled, reviewed, and merged.
