### ISSUE TITLE
Research newsletter options for OMB

### ISSUE THREAD

**Issue by nicoleslaw** [18F/omb-eregs#244]
Check with #outreach and #infrastructure

**Comment by yowill** [comment]
From initial discussions with Matt, ideally: 
- The ability to publish occasional news, feature updates, downtime alerts out
- The ability to collect responses from the readers (but not a listserv), so they can just respond to the email for help
- Web sign up would be cool
- Able to support “hundreds” of users, .gov and non-.gov
- Free or cheap :)

**Comment by nicoleslaw** [comment]
Sharing some notes here. Erik B advised that MailChimp is still in the GSA approval process (not sure about other agencies), but the process with GSA is pretty extensive.

Holly advised:

> A week or so ago a few of us were in a demo of ServiceNow, which has fedramp authorization and was incredibly fully featured. It has *more* than is needed but is ready to go. @mogul was our “lead potential customer” in that demo.

**Comment by nicoleslaw** [comment]
Andre from our Outreach Team mentioned:

> Just want to throw out that the GSA listserv instance is very basic and not very user friendly. It might be ok for status/outage updates, but the experience really feels like it's from a previous decade. And it's difficult to customize. We used it for a bit for the 18F newsletter, then switched to GovDelivery. GovDelivery is not approved for our use for some reason, but tons of other agencies use it, and OMB might be able to get that easier than MailChimp depending on their process.

> GovDelivery is a pretty good platform. Easy for non technical people, decent customization, can still get analytics and do A/B testing. Doesn't feel as modern as MailChimp, but totally fine for an informational newsletter.

**Comment by nicoleslaw** [comment]
@theresaanna I gathered some suggestions and comments in the thread above. Do you have any other suggestions for this task? Should we make a recommendation, or is this enough detail to help OMB make a decision?

**Comment by nicoleslaw** [comment]
@yowill Do you need anything else from me on this one?

**Comment by yowill** [comment]
Hold until next round to dive deep and execute
