### ISSUE TITLE
Determine what to do with admin UI requests

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#246]
These are requests from OMB regarding the admin side that we need to make decisions on:

- [ ] List policies by status
- [ ] List of requirements by deadline
- [ ] Need to search for the policy ID as well as the memo ID
- [ ] Need the full title of a policy in the backend
- [ ] After editing a requirement the next screen should take you back to the list of requirements in a policy, not the overall requirements list
- [ ] This is a difficult one: editing multiple requirements at once would be great.  The lag in loading a page makes it difficult to edit multiple requirements in a policy.

**Comment by theresaanna** [comment]
This needs to be split out and delegated.

**Comment by theresaanna** [comment]
New issues created, added to Backlog milestone.

**Comment by cmc333333** [comment]
<3
