### ISSUE TITLE
Page inventory

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#247]

**Comment by micahtaylor** [comment]
WIP doc - https://docs.google.com/a/gsa.gov/document/d/1uUoOyT8TMhTo-Ut15LRd7lA3HrH0Vi3wSmpDV4k3BzY/edit?usp=sharing

**Comment by nicoleslaw** [comment]
Looks good so far! I added some suggestions and edited the `Detail` section a bit.

**Comment by micahtaylor** [comment]
Great! I'm happy to close this and work in the doc.
