### ISSUE TITLE
Clean up feedback from OMB

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#251]
- ~~Hide password in admin user view.~~ #252
- ~~Remove password field when MAX is in use.~~ #252
- Figure out a way to flag official guidance vs policy.
- ~~Policy podcasts.~~
- ~~Add memo ID near policy title — that is, near the bold text here, add the memo ID~~: 
![image](https://cloud.githubusercontent.com/assets/2626258/25106523/cf10e064-237e-11e7-832a-19e859bb07ef.png)
- ~~Potentially add memo ID to the list of properties on requirements, just after policy title.~~
- Add slug field to requirements and the ability to search/link by it. Potentially only show slug if present, requirement ID otherwise. See also #241.

**Comment by tadhg-ohiggins** [comment]
#252

**Comment by theresaanna** [comment]
This issue needs splitting out and assigning.

**Comment by cmc333333** [comment]
> Figure out a way to flag official guidance vs policy.

Is this different from the existing policy "type" field?

> Add slug field to requirements and the ability to search/link by it. Potentially only show slug if present, requirement ID otherwise.

This seems super sketchy still. I'd vote for removing it and see if it comes up again.

**Comment by cmc333333** [comment]
Per brief convo with @tadhg-ohiggins, I'm going to close this; we'll see if the remaining requests come up again.
