### ISSUE TITLE
Admin view slowness

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#258]
When viewing a policy with many related requirements (such as policy 1, “25 Point Implementation Plan To Reform Federal Information Technology Management”) the local development Docker instance takes a significant amount of time to load the page for that policy (over 30 seconds).

It's possible that a future Docker caching feature will improve this.

That page does over 60 database queries, and so while it's fine in dev and prod, we might want to improve that also. @cmc333333 suggested `select_related` or `prefetch_related` in Slack as possible avenues to follow.

**Comment by cmc333333** [comment]
This is almost instantaneous when we're in prod mode; may be another toolbar issue.
