### ISSUE TITLE
Wireframe how requirements could be displayed

### ISSUE THREAD

**Issue by jehlers** [18F/omb-eregs#29]
@donjo and I will post all of our ideas for discussion.

**Comment by jehlers** [comment]
@donjo and I started off this process by each going off in our own direction so we could come back and talk about what's working and what isn't. Here's my 4 wireframes from this first round.

### Requirements inside the policy document

Going through the CSV file, I had a very hard time completely divorcing the requirements from the whole policy document. Our research backs that up in that most agency users want to have access to the whole doc to make sure they get as much context and understanding for what they need to do. So I started wireframing out a potential policy document page:

![option 1](https://cloud.githubusercontent.com/assets/4267825/22796211/89500faa-eec7-11e6-9a7e-320c1f245ab9.png)

In this wireframe, we have the title of the document and some important metadata. Then we have a list of all the sections within the policy that could be expanded if needed. But, the requirements are pulled out in their own blurbs so you can quickly scroll through and see them all. You could also potentially search or filter them more by their tags and agencies. 

### Requirements inside the policy document — Take 2

For this (ugly) one, I was still in the same mental space as I was for the first wireframe. But, I wanted to integrate the requirements a little more into the document. I also really liked the concept of highlighting different parts of the requirement like *who*, *what*. 

![option 2](https://cloud.githubusercontent.com/assets/4267825/22796291/e9aa1440-eec7-11e6-8da6-e8bdafcce5f6.png)

### Searching for requirements

Then I wanted to move away from the policy document itself and focus more on the requirement text. So I thought about how someone may want to search for a requirement. They probably need more than one search tag or term. And then they would get a list of requirements that fits. They could then click into each requirement to get to the larger policy doc if needed.

![option 3](https://cloud.githubusercontent.com/assets/4267825/22796398/23134dbe-eec8-11e6-8ab9-10c881586a57.png)

### Thinking for future policy structures

In this design, I was aiming a little bit for how I wish policy was structured. In this case, I pulled out some of the metadata around the policy and tried to use plain language headers to explain their importance. Then the requirements are listed openly and quickly. I also added numbers to each requirement in the hope that it would make it easier for them to be edited and changed in the future. In theory, the rest of the policy doc or hopefully each explaination of each requirement would either be expandable below the requirement or put under the full list of requirements.

![option 4](https://cloud.githubusercontent.com/assets/4267825/22796482/74afbea0-eec8-11e6-9603-1f08e712ddda.png)

**Comment by donjo** [comment]
## Real language 

The idea here is that requirements should sound like they are written for humans, even down to the filters you are using to find them.

Requirements are broken down into their simple sentence form and each requirement is an atomic unit that can have a set of metadata associated with it (like due dates, tags for agencies, topics, and roles it applies to, or the policy they came from). They could also be converted into a working checklist that agencies could use as they think about how to implement the policies.

The filters presented may be established somewhere else (maybe there was a landing page and this is the "results" page) but the user should be able to create custom views for requirements that apply to them. They could modify any of those filters to see a different set of requirements. 

![screen shot 2017-02-09 at 12 23 06 pm](https://cloud.githubusercontent.com/assets/776987/22797062/93f80aca-eec2-11e6-8b0c-fce84b00822e.png)
![screen shot 2017-02-09 at 12 23 14 pm](https://cloud.githubusercontent.com/assets/776987/22797061/93f74c8e-eec2-11e6-8879-edbb3700a9f8.png)


## Search for requirements, expand for detail

This is an example of how requirements could exist as atomic units, each of which could be expanded upon for more detail. 

Extra detail could include any additional information OMB wants to provide about why a requirement was established, suggested tasks an agency could take on to meet the requirement (hire someone, set up a server, use a piece of software, report on something), how long they have to comply, and more. 

Requirements would be presented in list form with some sort of priority established (maybe based on due date, grouped by policy, etc.) 

![screen shot 2017-02-09 at 12 33 28 pm](https://cloud.githubusercontent.com/assets/776987/22797486/0a9b9bb4-eec4-11e6-9d38-ed563c88c079.png)
![screen shot 2017-02-09 at 12 33 21 pm](https://cloud.githubusercontent.com/assets/776987/22797487/0d03192c-eec4-11e6-919c-c5595fb96856.png)

**Comment by donjo** [comment]
Some more ideas from Friday:

## Three Column View

Filters on the left for building a requirements profile that's relevant to your role, requirements in the middle, more detail on those requirements in the right sidebar. 

![screen shot 2017-02-13 at 10 24 01 am](https://cloud.githubusercontent.com/assets/776987/22892007/b4980f48-f1d6-11e6-9fb3-9288069f7060.png)


## Tabbed viewer

Filters on the left to manage which set of policies you are viewing then the right hand side is a tabbed view where users have three different ways to look at the same information. The first is a checklist of requirements, distilled down into simple sentences. The second tab is a timeline view where you can see when requirements need to be met. Lastly, a policy view that will list all the memos, circulars, policy releases etc. that the filtered requirements came from where users can click through to read the full text.   

![screen shot 2017-02-13 at 10 30 43 am](https://cloud.githubusercontent.com/assets/776987/22892281/956f9d60-f1d7-11e6-9309-72101eaa15bc.png)

![screen shot 2017-02-13 at 10 30 54 am](https://cloud.githubusercontent.com/assets/776987/22892287/9ada02a4-f1d7-11e6-8a82-3f297df2512b.png)

**Comment by donjo** [comment]
Example of the policy tab showing which policies apply to the selected guidance profile filtered on the left side. 

![screen shot 2017-02-13 at 1 46 48 pm](https://cloud.githubusercontent.com/assets/776987/22900133/e9054a5e-f1f2-11e6-819d-e4ce6d41e586.png)

**Comment by jehlers** [comment]
More from Friday focusing on the navigation flow.

### Flow #1 - Searching

Starting from the homepage, maybe we could have the ability to both search for topics or browse through topics to help the user answer "what applies to me?"

![navigation 1](https://cloud.githubusercontent.com/assets/4267825/22903551/fe9339f8-f206-11e6-9146-60c8314700f5.png)

This pretty closely matches @donjo's sketch from earlier, but allowing people to search for topics and their agency or group in some way could help narrow down some requirements.  

![navigation 1a](https://cloud.githubusercontent.com/assets/4267825/22903586/1ee79a96-f207-11e6-87dc-cca8249bd392.png)

These topics and tags would show the user a list of requirements that apply (split across different policy documents).

![navigation 1b](https://cloud.githubusercontent.com/assets/4267825/22903707/90d0bc0a-f207-11e6-900b-2683f0c77c61.png)

Once you click into a requirement, it takes you directly to that requirement within the policy document. Maybe on the left we could list / navigate by requirement. We could also maybe re-list them in order of relevance or importance.

![navigation 1d](https://cloud.githubusercontent.com/assets/4267825/22903742/ac7cd0b0-f207-11e6-867f-66eec76f84b3.png)

### Flow 2 - Narrow down

I'm still having a hard time separating requirements from policy. So this wireframe focuses on starting with every policy available, and narrowing down based on what the user searches for. Each "card" is a policy document that lists the number of requirements. 

![navigation 2b](https://cloud.githubusercontent.com/assets/4267825/22903954/89fcdca0-f208-11e6-8968-3e9021a4fd9c.png)

Post search:

![navigation 2b](https://cloud.githubusercontent.com/assets/4267825/22903966/95063286-f208-11e6-8dba-9c8c8e37e5b6.png)

Once the user clicks into a policy, they get that list of requirements inside the policy. With potentially more ways to sort and narrow down.

![navigation 2c](https://cloud.githubusercontent.com/assets/4267825/22903973/a630d21e-f208-11e6-8c8e-69694696aa0a.png)

Once the user clicks into a specific requirement. I have 2 ideas. The first is focused on how policy is written now. Since each requirement is part of the larger text, we could show the whole text where the requirement lives and highlight the requirements around it. So you've then narrowed down from all the policies, to requirements, to the full text of the requirement.

![navigation 2d](https://cloud.githubusercontent.com/assets/4267825/22904048/ef137e6e-f208-11e6-8d3b-d665ef1bfda5.png)

In the future, ideally, each requirement would be the main point and background information related directly to the requirement could live directly below the requirement.

![navigation 2e](https://cloud.githubusercontent.com/assets/4267825/22904087/128f834c-f209-11e6-8b6c-8d535b8d92ab.png)

**Comment by jehlers** [comment]
Updates for the sprint demo on 2/17.

The following is based on all the work @donjo and I posted above, plus conversations with the rest of the team and our product owner. The wireframes represent the combined direction we are planning to take the tool (at least for an initial MVP).

## Filter and sort

Generally, everyone liked the idea of browsing through requirements and narrowing them down until you find the ones that apply to you. 

This wireframe uses the left sidebar to filter down requirements based on topic tags, agencies they apply to, reporting cycles, deadlines and or sunset dates.  Then on the right, the user has the ability to sort and see just a list of requirements OR see those requirements combined by the policy they are a part of.

The team believes this is a promising direction, but we have a lot of questions about what the right filters and sorting options are. I think what we have in this wireframe is a good baseline, but we plan on experimenting a lot with sorting and filtering in our initial prototype to see how well these options narrow down the many many requirements that could come up in this list. 

Here is the "requirement" sorting view:

![start](https://cloud.githubusercontent.com/assets/4267825/23070564/770a1b14-f4f9-11e6-8100-afe9065ec591.png)

If the user clicks to expand and "read more," they will see the rest of the meta data related to that requirement and probably a link to the PDF of the policy. The tags also show you how the requirement made it to the top of the list:

![filtering and expanding](https://cloud.githubusercontent.com/assets/4267825/23070757/2cfbc0bc-f4fa-11e6-89bb-3e28c50cecd1.png)

Here is the "policy" view:

![sorting by policy](https://cloud.githubusercontent.com/assets/4267825/23070787/3ebd9370-f4fa-11e6-99da-3c7e8cce5bda.png)

In the policy view, I think the expand interaction from the last wireframe could work the same way. Then if the user wanted to dig deeper into the policy, they could click on the larger group.

## Digging deeper into policy

Thinking beyond just the requirement level, our research says that users want and need to read more deeply into the full policy document. In this wireframe, instead of the expanding feature, if the user clicks "read the policy" they will be taken into the full document.

![moving over to the policy document](https://cloud.githubusercontent.com/assets/4267825/23070926/af07d816-f4fa-11e6-974c-b7bfca65dab1.png)

Once they click to read the policy, the user would be taken straight to the requirement they had clicked on wherever it lives in the larger document. We could display the whole document, but highlight the requirements so that it is still easy for users to skim and skip around to find the parts of the policy that apply to them more deeply. If they want to dig deeper, they can always expand any section in the policy and read the whole thing:

![policy view 1](https://cloud.githubusercontent.com/assets/4267825/23071029/0bb2eb00-f4fb-11e6-93ad-96c1bb9c12d6.png)

The following wireframe is the same interaction in terms of reading the policy document, but instead of using the header as the document navigation, I've used the left sidebar to navigate through the document very similar to the way eRegs works now. We could pull out which sections have requirements so that users could skip to those even faster. 

Although I like this interaction, it is very true that these documents are very inconsistent. Some may be so short that they do not need left navigation, some may be long but don't have section titles, etc... So the ease of navigation you get with this kind of interface is great, but we need to see how well it applies to all policy documents.

![policy view 2](https://cloud.githubusercontent.com/assets/4267825/23071156/6b1a7752-f4fb-11e6-8532-5115a3deffd7.png)

And finally, here is the option to continue the expandable interaction and show more metadata around the requirement within the policy document:

![maybe we expand](https://cloud.githubusercontent.com/assets/4267825/23071181/7efe8790-f4fb-11e6-97a0-d544eb6b9701.png)

I think there still are a lot of open questions, but the above direction feels like a good place to start building a prototype. The prototype will allow us to re-asses these designs and figure out how to make it more navigable and useful for our users.

**Comment by yowill** [comment]
CLOSED!
