### ISSUE TITLE
Design homepage

### ISSUE THREAD

**Issue by nicoleslaw** [18F/omb-eregs#301]
We have a draft of the content ready for the homepage: https://docs.google.com/document/d/1GkTZf7TxvlJb7ofEEZOwe3oCrbHm7eyKG5OVqInxqIs/edit

I decided to make a new issue for ease of planning the visual design work (and we can have a separate issue when we're ready to test it).

**Comment by micahtaylor** [comment]
Still pushing pixels but ready for some eyes on the homepage - https://gsa.invisionapp.com/share/M6AU3YB49#/234185560_Homepage

**Comment by yowill** [comment]
Finished!
