### ISSUE TITLE
Fix issues raised by the Google Accessibility Developer Tools

### ISSUE THREAD

**Issue by theresaanna** [18F/omb-eregs#308]
<img width="797" alt="screen shot 2017-05-10 at 1 19 04 pm" src="https://cloud.githubusercontent.com/assets/126935/25919350/5665cb4a-3583-11e7-9c83-adc49b39d25f.png">

**Comment by cmc333333** [comment]
#407 and #409 solved all but two of these issues:

* [Severe] Elements with ARIA roles must ensure required owned elements are present (1)
An accessible autocomplete tool #g-accessibility pointed me to has the same issue, so I'm thinking this is a false positive.
* [Warning] These elements are focusable but either invisible or obscured by another element (1)
I think this is a false positive as it is visible through a transparent div.

I'd be in favor of closing this ticket as is.

**Comment by yowill** [comment]
@theresaanna Also, this task too, can you update us on the status?

**Comment by cmc333333** [comment]
@yowill I'll finish this one up.

**Comment by cmc333333** [comment]
With the latest version of our app and accessibility tools, we have only one warning on all of our pages:

<img width="846" alt="screen shot 2017-09-29 at 11 24 28 am" src="https://user-images.githubusercontent.com/326918/31023311-71b89314-a509-11e7-9b86-d45c53b1b592.png">

There are, however, a few more warnings with HTML Codesniffer which should be resolved before closing this ticket.
