### ISSUE TITLE
Demo for All-Hands on Tuesday, June 6th

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#362]
Outline: 
- Where we started (Tadhg)
- What we're doing now (Tadhg)
- What it looks like (Micah)
- How we're communicating with the customer (Micah)
- What we're going to do next (Micah)

- [ ] Create a 7-10 minute Google Docs demo of the work we did on this project and what we're going to launch in a few weeks
- [ ] Present it (figure out who)
- [ ] Wipe hands on pants and receive bacon

**Comment by yowill** [comment]
Slide deck to add to: https://docs.google.com/a/gsa.gov/presentation/d/1va53QL7QZkq_AHPV6xELdGy_Yiweg1TsPJLlHeC8lmQ/edit?usp=sharing

**Comment by cmc333333** [comment]
We definitely received bacon here. Well done, gents!
