### ISSUE TITLE
Review user research to date and create/make public a synthesized documentation of it

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#365]
verbs
- [X] read through existing research documentation and notes
- [X] write up a synthesis doc (user archetypes) 
- [x] have team (esp. Micah and Nicole) review and add comments/clarifications
- [x] publish on GitHub wiki

**Comment by carodew** [comment]
Temp google doc of user archetypes, to be converted to MD when closer to done: 
https://docs.google.com/document/d/1an4l3Pl9UgySeYPlQ6Cjh3x-lphhq-iycsTne11Qrec/edit#

**Comment by carodew** [comment]
Added a page to the research wiki here: https://github.com/18F/omb-eregs/wiki/OMB-policy-library-user-archetypes

@micahtaylor – would you be willing to review the page on the wiki and close this issue if you think it's good? No rush.

**Comment by micahtaylor** [comment]
Looks great to me! 💯 
Would love @nicoleslaw to look it over as well. Feel free to close it once you are done Nicole as it is a WIP.

**Comment by nicoleslaw** [comment]
All good! 👍
