### ISSUE TITLE
Heuristic evaluation of admin interface, focusing on quick wins

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#371]
Review pages in the admin interface and look for quick things we can change before release. 

Bonus – also come up with research questions.

**Comment by cmc333333** [comment]
Results are being put in https://docs.google.com/document/d/1jpLJDbhgn8PyzEH5TN6ShmiOIXv9ZvbVEyzVpGzCq88/edit

**Comment by cmc333333** [comment]
@carodew did the initial review and we implemented several updates in #381 and #395, so I'm going to close this.
