### ISSUE TITLE
Implement privacy page

### ISSUE THREAD

**Issue by nicoleslaw** [18F/omb-eregs#425]
OMB would like to reuse the text from this privacy policy for the new OMB IT Policy Library: https://www.fpc.gov/privacy/

We should replace any references to `fpc.gov` with `OMB IT Policy Library`. I am checking with our partners to see if there are any other changes we should look out for, but I think it's safe to build this in HTML and we can continue editing later.

**Comment by micahtaylor** [comment]
First high-level pass implementing content from https://www.fpc.gov/privacy/

![localhost-8002-privacy](https://user-images.githubusercontent.com/671894/28841826-0d3c176a-76c1-11e7-9da3-2eb4e846a7b9.png)

**Comment by carodew** [comment]
We didn't actually build on Sites, though, correct? I'd be happy to help update the Security section (although would need help from those with more tech knowledge to make sure it's accurate). 

I know @nicoleslaw is knee deep in a couple other projects but I have some bandwidth and can pinch hit at content if need be.

**Comment by carodew** [comment]
PS. If I'm diving in too fast before you're ready @micahtaylor – feel free to rebuff me.

**Comment by micahtaylor** [comment]
Might be easier to add to the review on https://github.com/18F/omb-eregs/pull/432/

**Comment by carodew** [comment]
Is this implemented? Is this issue something we can close?

**Comment by cmc333333** [comment]
I think we were waiting for OMB lawyers review at the time. If they didn't get back to us, I don't think they're going to.
