### ISSUE TITLE
homepage topic search allows arbitrary text search before load

### ISSUE THREAD

**Issue by mattbailey0** [18F/omb-eregs#434]
The topic list for the homepage topic search takes a couple of seconds to load. Prior to loading a user can search for an arbitrary string. The result is a blank search results page that doesn't provide much context for the user ([example](https://omb-eregs-demo.app.cloud.gov/search-redirect/topics/?insertParam=topics__id__in&redirectPathname=%2Frequirements&q=asdf)). From that page, using the full text search in the sitewide header results in a bad route like [this one](https://policy-beta.cio.gov/search-redirect/topics/requirements/?req_text__search=m-04-04&insertParam=topics__id__in&q=m-04-04&redirectPathname=%2Frequirements).

**Comment by micahtaylor** [comment]
@cmc333333 mentioned that the search issues was resolved in a PR. 
Here is the updated experience for blank search results.

![omb-eregs-demo app cloud gov-search-redirect-topics--insertparam topics__id__in redirectpathname 2frequirements q asdf](https://user-images.githubusercontent.com/671894/30282636-7d31b1bc-96db-11e7-878c-595727ab213f.png)
