### ISSUE TITLE
site <title> and name mismatch

### ISSUE THREAD

**Issue by mattbailey0** [18F/omb-eregs#436]
We have a bit of a content regression - the ```<title>``` of the site is "OMB IT Policy Library (Beta)" but the ```<h1>``` in the sitewide header has reverted to "OMB Policy Library Beta"

I am working through the most appropriate revision (given that we are now adding a subset of non-IT policy to the site) with internal stakeholders but we will need to either revise the h1 or possibly add a little clarifying language about scope and comprehensiveness to the "About this site" content on the homepage.

**Comment by mattbailey0** [comment]
@micahtaylor @nicoleslaw @carodew

**Comment by micahtaylor** [comment]
@mattbailey0 Just to clarify the `<title>` should match the `<h1>`, correct?

**Comment by mattbailey0** [comment]
Well it was all supposed to say "IT policy library" but now we are adding some non-IT policy. So stand by - I am working through some edits w/ other teams and will submit a PR

**Comment by mattbailey0** [comment]
https://github.com/18F/omb-eregs/pull/437

**Comment by mattbailey0** [comment]
(please take a look at formatting! i am stuck without a dev environment today)

**Comment by cmc333333** [comment]
Resolved with #437
