### ISSUE TITLE
Plan and execute kick off

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#443]
## actions 
- [x] settle on dates 
- [x] team scheduled travel 
- [x] secure a location 
- [x] plan activities 
- [x] invite stakeholders from OMB
- [ ] documentation of decisions and findings

**Comment by carodew** [comment]
Kick off agenda [WIP] – this link will only work for 18F folks – https://docs.google.com/document/d/14kFKvOLtnph6dT7K0VjSueJ3WfeNa0lwpBaPxziKE70/edit#

**Comment by carodew** [comment]
Notes from meeting – either The week of Sept. 11-15 or the week of Sept. 18-22

**Comment by yowill** [comment]
Pretty much done
