### ISSUE TITLE
View requirements in context of policy

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#445]
## User need
As an agency implementer, I don't think of requirements as separate from policy – I need to view any requirement within the context of the larger policy that contains. That way I can understand what it really means. 

## ac
- [ ] agency implementers can view individual requirements within the entire policy on the site
- [ ] the policy view makes it easy to read both the entire policy 
- [ ] a user can see the individual requirement 'chunks' in the policy view but this doesn't interfere with the experience of reading the entire policy
- [ ] in usability testing, users can easily find the full policy view directly from a requirement card 

## Supporting research 
[Round two research](https://github.com/18F/omb-eregs/wiki/Round-2-research-findings#users-need-to-understand-the-context-around-a-requirement-or-policy)
[Rounds 3-4 research](https://github.com/18F/omb-eregs/wiki/Rounds-3-4-research-findings#users-need-to-understand-the-context-around-a-requirement-or-policy-further-validation-from-round-2-findings)

**Comment by carodew** [comment]
related – https://github.com/18F/omb-eregs/issues/446#issuecomment-324359736

**Comment by carodew** [comment]
Note – as an intermediate step, we can display the information we have already as a policy 'detail' page – and add more data as we get it.

**Comment by yowill** [comment]
Did it, closing
