### ISSUE TITLE
Link to individual requirement

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#446]
As an agency implementer, I want to share the exact requirement language with my colleagues. Sometimes I just want to call someone's attention to an individual requirement, but sometimes I want to call attention to the requirement within the context of the entire policy. 

## ac 
- [ ] users can copy/paste the link to an individual requirement from the navigation bar on their browser
- [ ] same thing, but for an individual policy

## supporting research 
https://github.com/18F/omb-eregs/wiki/Round-2-research-findings#agency-implementers-send-others-both-an-entire-policy-for-context-as-well-as-specific-parts-of-the-policy

**Comment by billhunt-usds** [comment]
>(this defacto means they would be able to navigate to a page that shows an individual requirement)

Is this necessarily true? We've used [deep linking with highlighting](https://vacode.org/2.2-100/#B) on other projects and found it to be successful in guiding users while maintaining context.

**Comment by carodew** [comment]
@billhunt-usds – that's a good point! I'll update the issue to remove that wording.
