### ISSUE TITLE
Clarify or remove requirement and policy IDs from public interface

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#447]
## user need
As an agency implementer, I've never seen a policy or requirement ID before, and I don't understand what these mean. I'm also not familiar with the concept of a requirement in OMB policy. This confusion distracts me from understanding what a policy or requirement is actually saying. 

## ac 
- [ ] policy and requirement IDs are either removed from the public UI altogether OR 
- [ ] the UI clarifies what policy and requirement IDs are so that agency implementers can understand them (this assumes that they could eventually be useful to agency implementers, and not just internally to OMB) 

## supporting research 
-  https://github.com/18F/omb-eregs/wiki/Round-2-research-findings#the-requirementpolicy-ids-dont-make-sense-to-users
-  https://github.com/18F/omb-eregs/wiki/Rounds-3-4-research-findings#this-is-a-new-way-of-presenting-and-organizing-policies-and-that-unfamiliarity-initially-confuses-users-further-validation-from-round-2

**Comment by billhunt-usds** [comment]
Just a note: I'm curious as to the implications for unique identifiers here with regard to policy revisions. Most everyone in government is used to referring to particular versions of particular documents (`M-04-04` or `800-63-3`) as well as by a particular title/chapter/paragraph (`501(c)(3)`). The implications of a constantly-shifting set of requirements with identifiers should be considered in the context of edits to these requirements – what happens one goes away, is replaced, is updated? Do the identifiers change?

**Comment by billhunt-usds** [comment]
(For example, the surrounding paragraphs of `501(c)(3)` (nonprofit tax status) have been removed over the years, but that one was never renamed to match the new document flow because so many people are used to referring to it as such.)

**Comment by carodew** [comment]
I think these are good concerns! I was not on the project when the numbering scheme was created, so I don't know exactly how it was settled on but if I understand correctly it came from OMB. 

I also think if this is something we want to redesign it probably should be tracked in a separate issue, since this is mostly how it's presented to external users in the public interface.

**Comment by yowill** [comment]
Closing since we're redesigning in future
