### ISSUE TITLE
Are there interface or interaction patterns we can learn from from similar products? Is there open source code we can borrow from other projects? (formerly "Bill Hunt research follow up")

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#452]
- [ ] Check out the list
- [ ] Dig through it
- [ ] Analyze if there are similarities or things we could borrow
- [ ] Don't make it a formal affair

**Comment by carodew** [comment]
I'd like to add these sites that @nicoleslaw looked at for inspiration about the reading experience – 

http://www.fastforwardlabs.com/brief/?url=the-hunt-for-el-chapo
https://thecreativeindependent.com/approaches/on-being-economical/
https://genius.com/8916027
Kindle
Readmill
Google Books (right-side scrubber is nice)
http://archives.cjr.org/the_kicker/sunlights_scout_is_a_promising.php

For clarity – should we rename this issue as 'related products research' ?

**Comment by nicoleslaw** [comment]
(Please say hi to Bill for me 👋 )

**Comment by krues8dr** [comment]
(Hi @nicoleslaw !!! :wave:)

I'm happy to chat informally or formally or very formally (black tie) about that list btw. I'm mainly coming from legislation / law and some of my ideas may not transfer to policy. Though we are reinventing some ideas about policy over here too so :shrug:

**Comment by yowill** [comment]
@theresaanna We were wondering in sprint planning what's the status of this, can you update us?

**Comment by theresaanna** [comment]
This is still in progress. I've made some movement but haven't finished. It's my top priority. I am maybe 2 hours from completion.

**Comment by yowill** [comment]
Presented and closed!
