### ISSUE TITLE
Add a Favicon

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#454]
We'll need to figure out which icon to use -- whitehouse.gov? cio.gov? something else?

**Comment by micahtaylor** [comment]
I'm proposing we keep it simple and utilize the star that is in the seal and is hinted in the design - https://gsa.invisionapp.com/share/M6AU3YB49#/235212241_Homepage3

[OMB-policy-lib.ico.zip](https://github.com/18F/omb-eregs/files/1282671/OMB-policy-lib.ico.zip)

**Comment by micahtaylor** [comment]
[OMBfavicons.zip](https://github.com/18F/omb-eregs/files/1335103/OMBfavicons.zip)
Updating favicon with a different generator.

**Comment by cmc333333** [comment]
Finished with #495
