### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by micahtaylor** [18F/omb-eregs#467]
https://github.com/18F/omb-eregs/issues/434 reminded me that we don't have a 404 page.
Need a template and content for a page not found.

**Comment by micahtaylor** [comment]
Static page template with 404 content.
https://gsa.invisionapp.com/share/M6AU3YB49#/252515643_Static_Page

**Comment by carodew** [comment]
@micahtaylor did you want me to take another look? I did, and it looks good!

**Comment by micahtaylor** [comment]
Adding @cmc333333 to thins as I know he is doing some work around static pages as a preface to this issue.

**Comment by cmc333333** [comment]
Implemented via #477
