### ISSUE TITLE
Add clarification that the site is a work-in-progress

### ISSUE THREAD

**Issue by krues8dr** [18F/omb-eregs#480]
We've been getting some feedback on the site, but many people do not understand that the site is not complete and that not all policies have been entered yet.

> I like the ease of use of the website, but it appears many policies are missing. For example, I searched both "buy american' and "regulatory reform" and there were no results. Would have assumed at least this memo would have come up for Buy Amercian and this one for Reg Reform. If you're asking for feedback on your competition, I'd still go with a Google search.

> I just tried to find some information on “FITARA” but it wasn’t  in the list of search items. 

> Also, is this pulling from test data or real data?  When I chose category management, it only showed two items and there have been numerous historical memos issued on strategic sourcing which should pull for this topic.  I also see no category for Federal Acquisition Certifications and there have been many memos issued on this topic.

It looks like we need to make it more obvious that this is not all of the policies, and we're working on that.  Perhaps a banner at the top of every page, or at least a very unignorable note near the search & results?

**Comment by micahtaylor** [comment]
<img width="1274" alt="screen shot 2017-09-20 at 10 18 55 am" src="https://user-images.githubusercontent.com/671894/30649027-7d475076-9ded-11e7-8ed1-81c880a66c9d.png">
We can surface the beta message info "above the fold". Updated design to come.

**Comment by micahtaylor** [comment]
It's also worth mentioning that we should add more helpful content in this section about the data and the current status of the site being in flux.

**Comment by carodew** [comment]
Other examples – 

"We’re designing this site in phases. [Share your feedback](#)."

or something like: https://clinicaltrials.gov/

https://www.gov.uk/service-manual/design/alpha-and-beta-phase-banners#example (except I personally don't like the word beta) 

(samples from @nicoleslaw ) 

So maybe something like "We're designing the site and adding policies in phases. [Share your feedback](#)." ??

**Comment by carodew** [comment]
It might also be good (but a separate issue) to have a note about it on the "no search results" page? 

Something like "Nothing matched your search term. We're still in the process of adding documents, so it's possible that what you're looking for isn't in our system yet. [Let us know what's missing](#)."

**Comment by micahtaylor** [comment]
Relating issue #467

**Comment by micahtaylor** [comment]
![offical header banner beta open](https://user-images.githubusercontent.com/671894/30762099-3f172230-9fa6-11e7-903b-a0761f333527.png)
Removing the toggle and bring the "beta" information to the top.
