### ISSUE TITLE
Have conversations around restructuring data 

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#491]
## User Story
As a CM or Tadhg, I want to figure out how to restructure the data so that it can be semantically organized and in Comic Sans.

## AC:
- [x] Review examples of different models
- [x] Come up with a basic structure and strategy
- [ ] Note exceptions to the rule

**Comment by cmc333333** [comment]
Our initial goal is to organize the document into chunks in a tree. We'll allow those chunks to be designated as a heading, a requirement, or general text. We've talked through a few editing interfaces, including a prose-mirror based [prototype](https://18f.github.io/omb-eregs-prototypes/demo03/editor/), but wanted to focus on the data structure for this sprint.
