### ISSUE TITLE
travis-ci.org blocked @ OMB

### ISSUE THREAD

**Issue by TheLastQuestion** [18F/omb-eregs#5]
https://travis-ci.org/18F/atf-eregs seems blocked from WH/OMB network. Is there an easy way to get it white-listed?

**Comment by cmc333333** [comment]
Hey there @TheLastQuestion,

Would you mind checking if https://circleci.com is also blocked? Travis is a German company, which might explain the block. This particular team's spent more time with Travis, but Circle and Travis are comparable.

If both are blocked and we can't get them whitelisted, you all won't be able to see the continuous integration logs (though you'd still see whether or not the tests passed). That's certainly not ideal, but also not _essential_.

**Comment by cmc333333** [comment]
Any news @TheLastQuestion?

**Comment by TheLastQuestion** [comment]
seems that https://circleci.com/, at least the front page, is not blocked.

That said, agree that it's not a big deal one way or the other. 

thanks for following up!
