### ISSUE TITLE
Replace topic search with full text search on home page.

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#514]
Per the [latest designs](https://gsa.invisionapp.com/share/QUDR1NBCK#/screens) and as part of #448, we'd like to replace the Topic-based search on the homepage with a full text search. We'll want to tweak the copy a bit to match that design.

Don't worry about the "View all topics" link.

**Comment by carodew** [comment]
No problems if you want to get started on this but note that the designs aren't final yet – particularly on the search results page and beyond. So just know that there may be tweaks! 

The homepage is testing a lot better so I don't think there will be huge changes there.

**Comment by rememberlenny** [comment]
I accidentally did this ticket too https://github.com/18F/omb-eregs/pull/520
