### ISSUE TITLE
anchor link to a paragraph within a policy document

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#528]
As an agency implementor, I want to send someone a link to a specific part of a policy, so that they don't have to search a large policy document to find the text I'm sending them to. 

## ac 
- [ ] user can link to a paragraph within a policy document
- [ ] this option is provided in the UI for users who don't understand URLs
- [ ] when the recipient of this link clicks on it, they can easily see at a glance which part of the text they've been sent to.

**Comment by carodew** [comment]
Pulling this into this sprint to start design work.

**Comment by carodew** [comment]
For reference – it would be ✨  great  ✨  to tie in analytics to this type of linking because it would be a concrete way to learn about what kinds of links people are sharing, aka, what content is the most important to users. I'm wondering if we could track – 

1. most commonly links created (aka – which paragraph/block level element has users clicking on "copy link to this paragraph" button the most) 
2. Which paragraphs/block level elements show up the most as the first view of a session – aka which ones show up most often as the entry point. (the assumption here is that a person received a link to that paragraph from someone else and clicked on it.

**Comment by rtwell** [comment]
## Button
![image](https://user-images.githubusercontent.com/12564977/32613993-ddb8c51e-c531-11e7-956b-22498c35624b.png)

## Hover
![image](https://user-images.githubusercontent.com/12564977/32614050-fc21cbfe-c531-11e7-8b34-6cc55b6c5f99.png)

## On click
>to come<

**Comment by rtwell** [comment]
@carodew  @cmc333333 @rememberlenny looking for your recommendation on how to dismiss that `on click` state. Does it fade after a few seconds? Clicking somewhere else clears it?

**Comment by rtwell** [comment]
## When a user comes to a policy after clicking a shared link / specific URL
![image](https://user-images.githubusercontent.com/12564977/32615268-f81149c4-c534-11e7-9afb-7a55198d9cc2.png)
## Mobile
![image](https://user-images.githubusercontent.com/12564977/32615332-212a4fb8-c535-11e7-978c-97763f92a6cc.png)

SVG for the little bookmarky guy
[bookmark.zip](https://github.com/18F/omb-eregs/files/1458271/bookmark.zip)

**Comment by cmc333333** [comment]
Designs complete and implementation ticket (#666) has been created, so closing.
