### ISSUE TITLE
Plan review by React expert

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#53]
We don't have deep expertise in React, so let's schedule a time for architecture review with an expert at 18F. Delaying the actual discussion until Sprint E so that we have something to review.

**Comment by cmc333333** [comment]
Scheduling this now

**Comment by theresaanna** [comment]
@cmc333333 did you get a chance to schedule this? I can take it on if not.

**Comment by cmc333333** [comment]
@adborden says he's in. I figure we'll send him our code at the end of this sprint, give him some time to review, then regroup towards the end of next week. Sound good?

**Comment by cmc333333** [comment]
We've got the plan: We'll send this repo over to @adborden and @jeremiak today with a request to review the architecture over this week and we'll schedule a chat Thurs/Friday.
