### ISSUE TITLE
indicate when a specific requirement is outdated

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#534]
As an agency implementor, I want to be able to tell at a glance when specific parts of a policy are outdated, whenever they appear in the interface, so that I don't mistakenly follow outdated advice. 

## ac 
- [ ] users can tell within a [five-second test](https://articles.uie.com/five_second_test/) what parts of a policy are outdated, where ever they appear in the interface (search results, within the policy page, etc)

**Comment by krues8dr** [comment]
At least today, afaik only whole policies are outdated, not individual requirements.  The only exception here is when a later policy explicitly replaces/removes a requirement, or there is an explicit end date.

**Comment by carodew** [comment]
There are policies that say "Within six months" and "within three months" – so it's conceivable that a policy is issued with those words, four months pass, and one requirement is outdated while one is still in play. IDK if we have any current policies with that specific circumstance but I suspect it's possible.

**Comment by krues8dr** [comment]
In most cases, these are almost always deliverable deadlines, not actually a requirement expiration, fwiw.  Just because you missed one of these doesn't mean you don't have to do it. :)

**Comment by krues8dr** [comment]
I'm just trying to get at - these are probably very rare right now, not a major use case.

**Comment by yowill** [comment]
Closing since we're redesigning in future
