### ISSUE TITLE
Develop “policy” page with all requirements

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#542]
In shifting to a policy-centered view instead of a requirements-centered view, we need a page that acts as a “policy page” that includes all of the requirements for that policy.

This is an interim solution to handle the current situation where we do not have full policy text, but do have requirements that have been extracted from a policy.

This is more or less a list of all the requirements belonging to a policy, showing the full text of each requirement.

**Comment by cmc333333** [comment]
With #545, we have a base for this page. I've created a bunch of related tasks to improve that view, so I _think_ we can close this. Please re-open if not!
