### ISSUE TITLE
Determine document structure/metadata format

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#544]
Moving to a policy-centric approach means we need:

- [ ] A document structure for policies.
- [ ] A metadata structure for policies and requirements.
- [ ] An outline of how to relate policies and requirements.

These are all on the development side; this issue doesn't address the design side.

**Comment by cmc333333** [comment]
Per our pair coding session, we're going to take the simplest approach and add a `OneToOne` relationship between `Requirement`s and `DocNode`s. I'll finish up the serializer + tests while @tadhg-ohiggins works on an importer/converter script (#555).
