### ISSUE TITLE
Policy detail: Better Metadata

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#549]
On the Policy detail page, we're currently displaying the requirement id, and an ordered list of topics. Let's clean that up based on this [early prototype](https://gsa.invisionapp.com/share/QUDR1NBCK#/screens/256032982):

* Relabel the Requirement id field
* Add the "Applies to" field ("impacted entity" in the data)
* Turn topics into links (to a list of policies with that filter)

Don't worry about sunset date at the moment -- that applies to the policy as a whole, so we likely won't want it on a specific requirement.

**Comment by rememberlenny** [comment]
@cmc333333 On it!

**Comment by rememberlenny** [comment]
<img width="1044" alt="screen shot 2017-10-11 at 5 58 13 pm" src="https://user-images.githubusercontent.com/1332366/31468909-cee8789e-aead-11e7-8c8e-f364999a5fd0.png">
