### ISSUE TITLE
Policy detail: add in-page anchors to requirements

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#553]
The current policy detail page allows a user to click between focused requirements, but doesn't add a hash to the url for scrolling. If a user selected a requirement low on the page and then passed that link to a friend, the friend would not know that they needed to scroll down.

To solve this, we should ensure that each requirement has a unique (DOM) id and include that id in the URL/href. We should also verify that the browser jumps to the correct element when loading such a url.

**Comment by yowill** [comment]
Just for the document page in this task
