### ISSUE TITLE
Policy detail: Incoming link

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#556]
Per Slack [conversation](https://gsa-tts.slack.com/archives/C3HKL8MS7/p1507754840000293?thread_ts=1507754115.000618&cid=C3HKL8MS7), we want the circles on the policy listing page to link to their respective policy detail pages.

**Comment by cmc333333** [comment]
We're not comfortable with the implementation of the full policy page yet, so we've delayed this.

**Comment by yowill** [comment]
Need to map the journey to spec out how this interaction takes place.

**Comment by cmc333333** [comment]
We'll need to take into consideration that most policies don't have the full document imported. I suspect we can add a clause to our db query to include that info (so we can decide on the frontend how to display). Other options include redirecting in the UI if the document data doesn't exist.

**Comment by cmc333333** [comment]
@micahtaylor says

> Perhaps it's time to remove the circle and focus on the numbered requirement link. The title can link to the policy detail view and the "view original document" can link off to originating document in the wild.

<img width="716" alt="screen shot 2017-11-14 at 11 35 08 am" src="https://user-images.githubusercontent.com/326918/32795231-1802d196-c939-11e7-9a5d-414997043f42.png">


Also: no link in the title if we don't have the document.

We can split off the "Remove requirements" bits into a separate ticket, if desired.
