### ISSUE TITLE
view tables within policy text

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#564]

**Comment by carodew** [comment]
So as we dig in, the content that is presented in a table in M-16-19 isn't actually tabular content, and seems to be presented in a table here because that's the tool the author had to display it. 

That being said, we think we should solve for the content that is within this policy document (in the spirit of solving for one policy that can be shopped around as quickly as possible), and then revisit designing for tables when we're ready to tackle it in a systematic way.

**Comment by rtwell** [comment]
for reference, here is the table from M-16-19:
![m-16-19 table](https://user-images.githubusercontent.com/12564977/32179601-d3ec4f32-bd5d-11e7-9ba0-ca8011bf36a7.png)

**Comment by rtwell** [comment]
one possible solution—nothing final:
![image](https://user-images.githubusercontent.com/12564977/32190783-f2a68c16-bd7c-11e7-9d6c-c7314df9772f.png)

**Comment by rtwell** [comment]
@carodew @cmc333333 @rememberlenny here's how another project handled some tables: https://seedfund.nsf.gov/awardees/phase-1/

**Comment by cmc333333** [comment]
@tadhg-ohiggins will make a first pass at implementation without restructuring the table

**Comment by cmc333333** [comment]
@tadhg-ohiggins implemented a first pass in #610, but it doesn't match the ["gold" design](https://user-images.githubusercontent.com/12564977/32123210-fc7e6192-bb28-11e7-956f-abf8279fba0e.png). Bill's said we shouldn't blow up the table yet.

**Comment by rtwell** [comment]
@cmc333333 @tadhg-ohiggins 
![image](https://user-images.githubusercontent.com/12564977/32563884-084493f4-c478-11e7-8226-c0cc59694f5b.png)

**Comment by cmc333333** [comment]
#671 styles these and Micah approved, so closing.
