### ISSUE TITLE
view math equations within policy text (?)

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#565]
is this what we mean by maths?

**Comment by cmc333333** [comment]
Heads up that one strategy here is to rely on [KaTeX](https://khan.github.io/KaTeX/), which renders most of TeX's math instructions. Might look like:

<img width="282" alt="screen shot 2017-10-23 at 1 22 15 pm" src="https://user-images.githubusercontent.com/326918/31903175-5a925e00-b7f5-11e7-8a01-e603db52c952.png">

**Comment by cmc333333** [comment]
@tadhg-ohiggins will take a first pass at implementing these equations. Major decisions include:

1. We'll move the footnote _out_ of the math script to make this a little easier

I'd recommend https://khan.github.io/KaTeX/. There are a few react-katex libraries, but I think they're all outdated.

**Comment by cmc333333** [comment]
@tadhg-ohiggins implemented a first pass in #609, but we've noticed some wonkiness around text sizes.

**Comment by cmc333333** [comment]
I think #634 and #645 finish this.

**Comment by cmc333333** [comment]
All merged; closing.
