### ISSUE TITLE
view policy footnotes

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#566]

**Comment by carodew** [comment]
Regarding footnotes, we want to be sure we don't dump screen reader and keyboard users at the end of a page without providing them a way to easily get back to where they left off in the text. 

![screenreader - footnotes](https://user-images.githubusercontent.com/10144074/31823204-4c1490a6-b579-11e7-8ad7-bc0d0eb0175d.png)

(comment copied from #527 )

**Comment by carodew** [comment]
one bit of inspiration – https://harvardlawreview.org/2017/10/bureaucracy-and-distrust-landis-jaffe-and-kagan-on-the-administrative-state/

**Comment by rtwell** [comment]
lil bit of crossover with #527 

![image](https://user-images.githubusercontent.com/12564977/32124588-e8aea1cc-bb2d-11e7-98df-559efe438e43.png)

**Comment by cmc333333** [comment]
@rememberlenny will take on implementation. Major decisions include:

1. Only one footnote should be open at a time
1. We'll start by shifting content around (rather than overlaying the footnote on existing content)
1. Sequential footnotes should be merged together, e.g. "Footnote 4, 5, 6" should be a single button if they're adjacent.
1. Footnotes should also appear at the bottom of the document

**Comment by carodew** [comment]
@rememberlenny @rtwell do we have or need to have text styles for the list of footnotes at the bottom of the document?

**Comment by rtwell** [comment]
@cmc333333 ask and ye shall receive

Sketch file [footnote-specs.zip](https://github.com/18F/omb-eregs/files/1434728/footnote-specs.zip)

![footnotes-compiled](https://user-images.githubusercontent.com/12564977/32283839-7ddc87b4-bef3-11e7-82e1-e068427aedf2.png)

**Comment by cmc333333** [comment]
We're a far way from this on the implementation front. I'd recommend we split this into smaller issues. Maybe:
1. Display footnotes at bottom of page
2. Interface around displaying a footnote when clicked
3. Only allow one footnote to be opened at a time (depends on 2)
4. Combine sequential footnotes (depends on 2)

**Comment by rememberlenny** [comment]
Closing in place of the newly created subtasks.
