### ISSUE TITLE
Design Incomplete Data View 

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#569]
AC:
- [ ] Clearly state that it's Incomplete data
- [ ] Look slightly different than complete data to indicate this status

**Comment by carodew** [comment]
unlinked version of what we currently have for good ole m-16-19: https://omb-eregs-demo.app.cloud.gov/policy/269

**Comment by carodew** [comment]
This might turn into a separate issue, but I've found two different ways for how the data are showing footnotes today. We'll want to find a consistent way to treat footnotes in both the incomplete data view as well as full policy text. 

![footnotes today](https://user-images.githubusercontent.com/10144074/31948326-995a5fac-b8a4-11e7-8e25-5eab1c19e26e.png)

**Comment by carodew** [comment]
In progress wireframe – 

![incomplete data policy page](https://user-images.githubusercontent.com/10144074/31963435-9dcfca16-b8ce-11e7-9849-2bdad54cd3fd.png)

**Comment by carodew** [comment]
Relevant task flow – 

![find specific requirement](https://user-images.githubusercontent.com/10144074/31963782-de759400-b8cf-11e7-8ea7-b9b265a516f9.png)

**Comment by carodew** [comment]
![image](https://user-images.githubusercontent.com/10144074/32122003-e1013314-bb2c-11e7-8678-8030b132de56.png)

**Comment by carodew** [comment]
@rtwell shared inspiration for copy-link/text interactions from https://unsplash.com

![image](https://user-images.githubusercontent.com/10144074/32280449-47c7ed18-bef2-11e7-9f53-b2d9de862eae.png)

**Comment by carodew** [comment]
Note - per convo in stand up yesterday we're pausing all work on the incomplete data view until and if the need arises again. So this work is on hold.

**Comment by carodew** [comment]
closed bc we're likely never doing this, and if we decide to do this we can create a new issue.
