### ISSUE TITLE
 Add admin users (for ourselves and one for Matt)

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#58]

**Comment by cmc333333** [comment]
I'm not sure if this should wait until #36 is finished or if we should give them access after the demo today.

**Comment by theresaanna** [comment]
@cmc333333 @yowill is there a list of folks who need access?

**Comment by cmc333333** [comment]
@theresaanna let's just say Matt for now -- it's easy enough to add users for ourselves when needed.

Be sure to coordinate w/ @tadhg-ohiggins here; he's been working with the demo and prod databases.

**Comment by cmc333333** [comment]
Matt's account has been created
