### ISSUE TITLE
navigate within a full policy document (design-only)

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#585]
As an agency implementor, I want to be able to jump to specific sections within a policy document, so that I can find the content I need without having to scroll forever or click on multiple pagination links and hope I get to the right place. 

## acceptance criteria

- [ ] in usability testing, users are able to easily use the navigation to jump to desired parts of the policy document, tested on mobile and desktop. 

## outstanding questions we need to address before we start work

- [ ] Are we solving for just M-16-19 or do we need to account for multiple formats of policy documents? If the latter, we will need to do some sort of content audit to learn what types of formats/headers/sections exist in different policies.

**Comment by carodew** [comment]
pulling this into sprint Penne since design is mostly caught up with the other stories.

**Comment by carodew** [comment]
Sprint Q – wireframes only

**Comment by carodew** [comment]
# Mobile wireframes! 

## free up some screen space by hiding preamble details

Adding a 'within document' interaction area on mobile eats up more screen space, to compensate we can hide some of the details in the preamble. Future usability testing will let us know if there is content stuck in there that we should pull out and not hide, but I think this is a good first stab. 

![iphone se details-collapsed](https://user-images.githubusercontent.com/10144074/32632017-05529c06-c570-11e7-8f73-fc925978ed3a.png)
![iphone se details expanded](https://user-images.githubusercontent.com/10144074/32632021-0748abd6-c570-11e7-94b6-805f9d2eafeb.png)

## Within document navigation menu

Tapping the "Jump to section" opens up a navigation comprised of h1s and h2s. The navigation pane itself is scrollable, and the current section that's hitting the top of the document area is visually indicated in the navigation menu (for wayfinding/orientation). 

![iphone se menu-expanded](https://user-images.githubusercontent.com/10144074/32632071-3396c380-c570-11e7-9d57-eff2495c98a9.png)

If a user is scrolled down to the bottom of the document and then opens the navigation menu, we have two options. 

1. easy option – menu opens at the top and the user has to manually scroll to find the part of the document they're currently in. This is most likely good enough for users to orient themselves where they are in the doc. 

2. ✨  Awesome ✨  option – we automagically open the menu and then _vrrrup_ – scroll them down until the section they're in is within view. The scroll helps them orient to where they are in the navigation and document. 

![iphone se-menu scrolled](https://user-images.githubusercontent.com/10144074/32632247-de790006-c570-11e7-8505-97db16e8dfa5.png)



## Within document search 

This is a future sprint, but we should account for it/leave space for it
 in the design. 

![iphone se-search open](https://user-images.githubusercontent.com/10144074/32632225-c9acb4ce-c570-11e7-8e16-194f56c4c879.png)

**Comment by carodew** [comment]
## desktop wireframe 

And here's an option for desktop. Feedback welcome at this point, @rtwell will take it over for visual design before it's ready for implementation. 

Please ignore the fact that some of the text is blue, that's a blooper. 

![full policy page-within-doc-navigation](https://user-images.githubusercontent.com/10144074/32956604-334b3d6c-cb87-11e7-898e-714707d4f7fe.png)

**Comment by rtwell** [comment]
# Desktop
![image](https://user-images.githubusercontent.com/12564977/33221709-3bd4f33e-d117-11e7-945f-5fc18a74ae6a.png)

# Mobile
## default
![image](https://user-images.githubusercontent.com/12564977/33221763-bdc76368-d117-11e7-8f56-b9761e50e074.png)
## Details tab open
![image](https://user-images.githubusercontent.com/12564977/33221766-c7fd25d4-d117-11e7-88f8-855af94cc538.png)
## Search tab open
![image](https://user-images.githubusercontent.com/12564977/33221806-20cf7a9a-d118-11e7-9117-18284b47dcdb.png)
## Jump to section tab open
![image](https://user-images.githubusercontent.com/12564977/33221832-4bb7b916-d118-11e7-9e90-e73236ef7364.png)

**Comment by rtwell** [comment]
also, @cmc333333 @rememberlenny @carodew it'd be great if the Jump to section | Search this policy bar would stay sticky at the top of the page (but the OMB header bar would not be sticky).

**Comment by rtwell** [comment]
dun.
