### ISSUE TITLE
Remove Theresa from admin interface on dev and prod

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#587]
For both the dev environment, do the following:

- [x] Take a screenshot of the list of users showing that Theresa is in the list.
- [x] Edit the screenshot to obscure the email addresses.
- [x] Remove Theresa as a user.
- [x] Take a screenshot of the list of users showing that Theresa is no longer present.
- [x] Attach both screenshots to this issue.
- [x] Have another team member verify that the user is no longer present.

**Comment by tadhg-ohiggins** [comment]
Before:
![image](https://user-images.githubusercontent.com/2626258/32121980-ab27297e-bb13-11e7-9959-2413a062c027.png)
After:
![image](https://user-images.githubusercontent.com/2626258/32122015-ca030e58-bb13-11e7-8a7a-b413bcf53eb2.png)

**Comment by tadhg-ohiggins** [comment]
@cmc333333 Can you confirm that Theresa is no longer an admin user in dev?

**Comment by cmc333333** [comment]
Confirmed, thanks @tadhg-ohiggins
