### ISSUE TITLE
Play with and flesh out live prototype sorting stuff

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#59]

**Comment by donjo** [comment]
We used the live data to apply some basic styles to the text and see what kind of problems we may encounter.

In this example there is a particularly long requirement that would potentially need to be dealt with if users are to understand that requirements are intended to be small, atomic units. This could be done by re-writing, truncating, hiding content, etc.

In talking to the OMB team today we learned that requirements are intended to be no longer than 300 characters the majority of the time. Tabular data, images, or other things may change that so we'll keep watching that going forward. The example below _may_ be cleared up in the newer dataset as this was taken with November data.

![screen shot 2017-03-03 at 3 20 25 pm](https://cloud.githubusercontent.com/assets/776987/23569451/f86d448e-0024-11e7-9314-432d01b034d0.png)
