### ISSUE TITLE
Policy detail: List elements

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#600]
Ensure we have a reasonable rendering for list elements, numbered lists, etc.

Remaining tasks

- [ ] First indent should be 32px
- [ ] ~~Second indent should be 80px~~ @rtwell has said we can do 32px per level.
- [ ] It would be great if we could scale these indents on mobile (i can see them not needing quite as much space)
- [ ] Numbers bold and black please
- [ ] Slightly larger bullets, if possible (6px would be perf!)

**Comment by cmc333333** [comment]
There's an implementation now, but should check in w/ design before closing.

**Comment by rtwell** [comment]
## Mark up here for easy viewing:
![lists](https://user-images.githubusercontent.com/12564977/32563272-72568ce0-c476-11e7-9eff-ccd24f8743a4.png)
## List o things

- [ ] First indent should be 32px
- [ ] Second indent should be 80px
- [ ] It would be great if we could scale these indents on mobile (i can see them not needing quite as much space)
- [ ] Numbers bold and black please
- [ ] Slightly larger bullets, if possible (6px would be perf!)

**Comment by cmc333333** [comment]
Resolved with #647
