### ISSUE TITLE
[Usability testing] Full policy view

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#617]
## Framing questions / hypotheses
- Does the way we're displaying M-16-19 make sense to users who are familiar with the policy? 
- ~Are users able to effectively navigate the document while on mobile?~
- Users are able to clearly understand how to trigger/view footnotes and get back to the place they were in the main text. 
- what are the most important next features to develop in the full text policy? 

## How we'll know we're right
- in usability testing, we observe users able to navigate within the full text view on their mobile device without problems, frustration, or confusion
- in usability testing, users don't express confusion about the way information is displayed (particularly in footnotes and tables) 
- in usability testing, we observe users able to show and hide footnotes without frustration or confusion
- without prompting, users request specific added functionality _and_ are able to articulate how that functionality would help them do their job better (the latter part is the most important part)

## Dependencies
Dependent on implementation of footnotes, tables, and math for M-16-19

**Comment by carodew** [comment]
![img_0647](https://user-images.githubusercontent.com/10144074/32573651-ab25545e-c49c-11e7-92a2-b002a07786f3.JPG)


Sketched out a prototype flow for usability testing. The chicken scratches basically say I need the following screens – 

1. the full policy text in the mobile view, including footnotes (all collapsed) and table w/ footnotes. 
  - one footnote is a hotspot to toggle expanding/collapsing the footnote
2. The same screen, but with one footnote expanded. 

## stretch goal – 

3. all the above screens, but including the "Link to this paragraph" link throughout. One that is relatively easy to find is a hotspot to the next screen ... 
4. same screen, but with the confirmation box that the paragraph link had been copied. 
5. same screen, but showing the view that a person would get after clicking on a link they received from someone else. (Not sure if this should be the same or different paragraph, which one would be more confusing). 

cc @micahtaylor and @rtwell

**Comment by carodew** [comment]
After chatting with @rtwell we decided that we're better off just testing what is going to be implemented on the live site at this point, so Ryan can devote his time working on other visual design stuffs. 

My immediate to dos are – 

- [ ] confirm usability testing sessions scheduled via appointment slots (yay!)
- [ ] invite notetakers to each session
- [ ] add a video call to each session 
- [ ] write whatever communications I need to do to explain the things
- [ ] write the conversation guide
