### ISSUE TITLE
Authoring tool plan 

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#618]
- [x] Collect data and examples
- [ ] Preliminary subjects for user research identified
- [ ] Feature list drafting

**Comment by austinhernandez** [comment]
### Design artifacts:
* [Freehand](https://gsa.invisionapp.com/freehand/document/J3g9i239s ): this document is a first draft user flow of uploading to approval process 
* [Invision prototype](https://gsa.invisionapp.com/d/main/#/projects/prototypes/12532570
): this is the clickable prototype 
* [Authoring tool research plan](https://docs.google.com/document/d/1l13c_SCVb2xfW79esexPCGWugkGI0eLdBsfUn701QyY/edit# ): this document outlines the first round of research

### Examples / related software:
- https://github.com/opengovfoundation/madison-assets/blob/master/201607-editor-designs/madison-editor-scenarios.pdf
- https://18f.github.io/omb-eregs-prototypes/admindemo/
- http://pdf2md.morethan.io/

### Users:
Identified but not scheduled

**Comment by yowill** [comment]
Feature list next task: https://github.com/18F/omb-eregs/issues/682 

Interviews and protocol: https://github.com/18F/omb-eregs/issues/684
