### ISSUE TITLE
Paragraph requirements DESIGN work for M16

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#619]

**Comment by yowill** [comment]
(create new task for dev implementation when we're ready)

**Comment by carodew** [comment]
Link to the list of requirements we have in the database currently for M-16-19: https://omb-eregs-demo.app.cloud.gov/requirements?policy__id__in=269&topics__id__in=

**Comment by carodew** [comment]
Link to full policy text - https://omb-eregs-demo.app.cloud.gov/document/M-16-19

**Comment by rtwell** [comment]
## large screens
![image](https://user-images.githubusercontent.com/12564977/32631796-fa23342a-c566-11e7-8164-219050e98d64.png)

## mobile
![image](https://user-images.githubusercontent.com/12564977/32631817-09444688-c567-11e7-96af-dd0a3143ddb0.png)

**Comment by rtwell** [comment]
star svg
[requirement.zip](https://github.com/18F/omb-eregs/files/1459442/requirement.svg.zip)

**Comment by cmc333333** [comment]
Designs complete and implementation ticket (#668) has been created, so closing.
