### ISSUE TITLE
Interface around displaying a footnote when clicked

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#620]

**Comment by cmc333333** [comment]
Design is in [this comment](https://github.com/18F/omb-eregs/issues/566#issuecomment-340080892)

**Comment by cmc333333** [comment]
#629 did a good chunk of this work, thanks @rememberlenny!

Some remaining pieces that I see:
* Use real data. We're currently using a mock footnote, but real data is now available on `content.footnode_node`
* Add a close link to the bottom of the footnote.
* Style the inline footnote to match the design as closely as possible. This should not affect footnotes elsewhere on the page.
* Triangle cutout for the speech bubble. I'd bet this will be difficult, so I'm calling it out separately from the remaining styles.

**Comment by cmc333333** [comment]
@rtwell says that the last (the triangle cutout) isn't essential for shipping -- if we can't implement this sprint, let's split into another issue to prioritize.

**Comment by rememberlenny** [comment]
Finalized changes on the `content.footnode_node`, with exception to the triangle cutout.

**Comment by cmc333333** [comment]
I've moved the triangle cutout work to #651
