### ISSUE TITLE
Display footnotes at bottom of page

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#624]

**Comment by cmc333333** [comment]
Design is in [this comment](https://github.com/18F/omb-eregs/issues/566#issuecomment-341149927)

**Comment by rtwell** [comment]
## Quick markup with tweaks:
![footnotes](https://user-images.githubusercontent.com/12564977/32560474-5f26a8aa-c46f-11e7-9721-897b4633f5e7.png)

## Changes listed here for easy reference:
- [ ] Line at the top should be our blue (#1067A6)
- [ ] Lessen the indent 50%
- [ ] The footnotes themselves should be sans serif, and smaller @ `14px (.875em)` and the line-height should be` 18px (1.125em)` 
- [ ] The numbers are the same size as the text, except they are `bold` and `black`
- [ ] it looks as if the baseline between the numbers and the footnotes is slightly off, if we could make sure they are aligned, that would be fantastic!
- [ ] Text should not break the right margin
- [ ] URLs should wrap
- [ ] If possible, can we take URLs and roll them into the text before them? And if we could get sassy,  **if the link points to an external web page** use [this icon](https://github.com/18F/omb-eregs/files/1454628/external-link.svg.zip). **If the link points to a file of any kind**, use [this icon](https://github.com/18F/omb-eregs/files/1454621/external-file.svg.zip). Here's an example:
![image](https://user-images.githubusercontent.com/12564977/32560639-c6047502-c46f-11e7-921c-b33f5143d57f.png)

**Comment by cmc333333** [comment]
I've broken out the bits about external url linking to #656 and #657.

**Comment by cmc333333** [comment]
Closing per Micah's okay in #650
