### ISSUE TITLE
Design review of M-16-19 whist Ryan is afk

### ISSUE THREAD

**Issue by rtwell** [18F/omb-eregs#641]
@cmc333333  https://omb-eregs-demo.app.cloud.gov/document/M-16-19

# Footnote button
![image](https://user-images.githubusercontent.com/12564977/32628328-1b5d39a8-c55b-11e7-826d-e355d98dbd47.png)

1. type looking a little small: the computed size should be 10px
2. type should regular, not italic
3. it looks like the footnote button is forcing extra line-height:
![image](https://user-images.githubusercontent.com/12564977/32628867-da92fcee-c55c-11e7-84f9-88501e2c2214.png)

# Header levels
![image](https://user-images.githubusercontent.com/12564977/32628659-3bf4d10c-c55c-11e7-900e-ce2f4ee3c24b.png)

Leadership and Responsibilities = `h3`
Transition to Cloud and Data Center Shared Services = `h3`
Development Freeze for New and Current Data Centers = `h4`

This may mean switching a bunch of `<h>` tags around—sorry!

# Paragraph line height and spacing
I'd love to see some space between plain ol' paragraghs
![image](https://user-images.githubusercontent.com/12564977/32628777-98dc8a9a-c55c-11e7-936c-ca6faaa7f1a3.png)
normal `<p>` should be 16px/27, with 16px betwixt `<p>`

# H1 line spacing
<img width="509" alt="screen shot 2017-11-08 at 6 15 12 pm" src="https://user-images.githubusercontent.com/326918/32738023-aa4c4d14-c869-11e7-9285-5aeaedbcce26.png">
It looks like Chrome's computed line height doesn't match the css

# H2 and H3 should be different heights
The original image in #527 contained a bad copy-paste for font-size in ems. This should be adjusted to match the updated image.

**Comment by cmc333333** [comment]
I added the last two requests from DM conversations with @rtwell
