### ISSUE TITLE
Discuss site-wide color palette

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#648]
There's a bit of a mismatch between the pallet described in [this comment](https://github.com/18F/omb-eregs/issues/527#issuecomment-340073841) and our current USWDS color scheme. Let's select a single set of variables and use them site wide.

Some additional requirements:
* [x] accessible
* [ ] relatively easy to rebrand (meaning var names shouldn't be tied to color)

**Comment by cmc333333** [comment]
Take aways from meeting:
1. the pallet @rtwell should already include accessible combinations
2. we'll delete all of the uswds color vars
3. we'd still like a strategy for swapping colors/themes out. Ryan's contacting @donjo to get his strategy
4. we'd similarly like to have a consistent unit for spacing, font-sizes, etc. It may make sense to split that out into a separate issue.

**Comment by yowill** [comment]
Done!
