### ISSUE TITLE
Add external-url annotations

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#656]
The original PDF for M-16-19 (and no doubt many others) contain links to various URLs, but we don't have a way to display those. I'd recommend against automation as we don't have a good way to "fix" false positives.

Notes on visual implementation (from #624)
> Links should be blue #1067A6 an underlined.

> if the link points to an external web page use [this icon](https://github.com/18F/omb-eregs/files/1454628/external-link.svg.zip). If the link points to a file of any kind, use [this icon](https://github.com/18F/omb-eregs/files/1454621/external-file.svg.zip). Here's an example:
![image](https://user-images.githubusercontent.com/12564977/32560639-c6047502-c46f-11e7-921c-b33f5143d57f.png)

**Comment by toolness** [comment]
Relatedly, I noticed Brendan Sudol just posted this to Slack:

[Removing the external link icon from GOV.UK](https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/)

Specifically, it says:

> We’d assumed that there was a clear need for the external link icon, but in 4 years we’ve seen no evidence that backs this up, so we're going to stop using it.

That said, they don't explain what they did to determine that there's no evidence for the pattern.

**Comment by carodew** [comment]
It's more to do with OMB policy that says we have to indicate links to external sources. 

The icon is much less intrusive than the modal dialogue that says "hey you're leaving our site" which is already obvious to anyone who already knows what a link is, which is generally everyone who would click on a link in the first place. 

see https://policy-beta.cio.gov/requirements?policy__id__in=445&topics__id__in= 

(Requirement ID: 1341.58)
