### ISSUE TITLE
Link to policy detail if it has a slug but not an OMB policy id

### ISSUE THREAD

**Issue by toolness** [18F/omb-eregs#678]
I left this out of #661, so it still needs to be done.

I have some architectural thoughts on this:

1. It seems like it'd be useful to move the React propTypes for a "policy" object out to a separate module, and import it into any component that happens to need it.  Is this a good idea?

2. I feel like putting the logic for this functionality into the `PolicyView` component isn't a great idea--it makes it a bit harder to unit test, for one thing, and it also seems like the kind of functionality that other components might want to use. If a Policy were a regular JS class, I'd recommend adding an `asUrl()` method to it, which performed this functionality. But Policy is currently just a plain JSON-serializable object, as I understand it... So one option is to make a bunch of functions that take this object as its first parameter, while another might be to "embellish" Policy into its own full JS class. I also might be getting a bit architecture-astronauty here so let me know if I'm thinking about this too much.

**Comment by cmc333333** [comment]
I think making the policy into as full-blown class would make sense here, particularly if we'll be using it in multiple places (which seems likely). This approach was taken for document nodes, to some success.

I certainly appreciate your hesitancy to introduce OO, though. I struggle a lot with that balance.

**Comment by toolness** [comment]
Yeah! Ok cool, I will take a look at the document node class and try to replicate it for the policy, and use that to implement a solution for this issue.

**Comment by toolness** [comment]
Ok, the `Policy` class is added, but I just noticed that it looks like our serializer on the back-end doesn't actually expose the slug, so fixing this issue will require adding that one too.
