### ISSUE TITLE
Importing/editing policy workflow outline

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#683]

**Comment by yowill** [comment]
Related to MVP features and Austin's research

**Comment by yowill** [comment]
Clarifying the workflow: No approval workflow, just allow flagging for status

**Comment by yowill** [comment]
Bill's MVP wishlist for workflow:

- User uploads
- Makes edits
- Publishes it 
- Status of “just uploaded, submitted, public/final” etc. to show the level of completion

**Comment by yowill** [comment]
Closed, prioritization will happen in #727
