### ISSUE TITLE
Interview protocol and scheduling for authoring tool 

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#684]
- [x] Establish interview process
- [x] Schedule the meetings
- [x] Go over the prototype in InVision
- [ ] Do the interviews

**Comment by austinhernandez** [comment]
**https://docs.google.com/document/d/1l13c_SCVb2xfW79esexPCGWugkGI0eLdBsfUn701QyY/edit?pli=1#** 

3 interview slots scheduled for the week of the 27th

**Comment by austinhernandez** [comment]
[Interview folder](https://drive.google.com/drive/folders/1mL12tPbMjF0hao54y3SOsp9uIOUDoXCC?usp=sharing) — includes interview notes for notetakers and the conversation guide/protocol.

**Comment by yowill** [comment]
One rescheduled, but done
