### ISSUE TITLE
Design search results for search within policy (design only)

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#693]
Design should include – 

- Ability to type in a search word or phrase 
- display number of search results near the search text box
- search results should be highlighted within the policy document (we might decide that we turn off requirement highlighting when search is in play
- option to click or tab through individual search results

**Comment by carodew** [comment]
linking #694

**Comment by carodew** [comment]
We're asking about users' expectations for this functionality in usability testing this sprint, should be able to get some results/answers early next week and hopefully have some wireframes by the end of the week (fingers crossed!)

**Comment by rtwell** [comment]
## for shorter documents (those that arent paginated)
Basically, i stole how browsers handle searching on a page. 

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/b049df83-c7ad-4a25-a91f-502eda381c21)

## for longer, paginated documents
I think a standard "search results page" may work here to avoid dealing with pagination. The search results are simply snippets that allow users to jump directly to the instance of the word they searched.

Ideally, if a user clicked "back" they would return to their previous search results.
![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/afb2a0ab-1e1c-4001-ae72-fa8208d0956c)

**Comment by rtwell** [comment]
after talking with @cmc333333, we decided, for our first pass, we would return results by element—meaning if a user searched "data", and it appeared in a paragraph, the entire paragraph will be shown, and the word data would be in bold (regardless of the number of times it appeared in that paragraph). 

The same goes for footnotes. 

Tables, however get a bit tricky, so one solution might be to simply link to the title of the table, avoiding the difficulty of rendering a table (or row, or cell) in search results. 

![OMB-Search results by element.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/7d9272f1-6629-4457-8d76-ce6be841f747)

**Comment by rtwell** [comment]
Something else to consider: a tabbed view. We could sort search results by type (i.e. footnotes, tables, calculations (maybe?), paragraphs, and could easily expand to something like requirements:

![OMB-Search results tabbed.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/1c9e9987-d7ce-47c5-910e-12cf78b51fcb)
