### ISSUE TITLE
Document title never changes throughout site

### ISSUE THREAD

**Issue by toolness** [18F/omb-eregs#699]
I've noticed that the document title (i.e., the text on the user's browser tab, and what is announced to screen readers) is always "OMB Policy Library (Beta)".  It seems like we should add details about what particular page they're on, e.g. "Search results for 'data center'" or "M-16-19: Data Center Optimization Initiative (DCOI)".

This would make it particularly easy for folks who might have multiple browser tabs open, each on a different page of the site, but it's most important for visually-impaired users (see #700).

In the [React a11y talk](https://youtu.be/aW6Gayf2Pao), [`react-document-title`](https://github.com/gaearon/react-document-title) is mentioned as a nice component that makes this particularly easy, though perhaps NextJS already has something built-in.

**Comment by cmc333333** [comment]
I'd bet the `<Head>` tag w/ keyed attributes will be important here: https://github.com/zeit/next.js/#populating-head

**Comment by cmc333333** [comment]
Resolved by #776
