### ISSUE TITLE
Combine adjacent inline requirements

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#709]
When different requirements are adjacent to each other (either within the same paragraph or in adjacent paragraphs, bullets, subparagraphs, etc.) they should be visually combined into the same highlighted blob.

Rather than
<img width="730" alt="screen shot 2017-11-29 at 1 12 30 pm" src="https://user-images.githubusercontent.com/326918/33391429-08ce4de8-d507-11e7-8da6-50e49a3fdae1.png">

We should see
<img width="762" alt="screen shot 2017-11-29 at 1 12 54 pm" src="https://user-images.githubusercontent.com/326918/33391436-0db0cac0-d507-11e7-8a77-2a78b0173420.png">

**Comment by yowill** [comment]
Closing since we're redesigning in future
