### ISSUE TITLE
Spitballing session around inline requirements

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#711]
We're running into lots of problematic requirement text when trying to design requirement highlighting. For example:
* Multiple requirements sharing the same "intro" text
* Multiple, adjacent requirements
* Part of a requirement text is in a paragraph, part is in a footnote
* Requirement split across cells within a table

While we have tasks around pushing forward on highlighting text within the policy, it's worth regrouping to discuss this interface more. We'd like to ensure the needs around emphasizing requirements are met while limiting the number of special cases and noise.

**Comment by cmc333333** [comment]
Email to schedule w/ Bill sent. I'd like to regroup with at least @rtwell beforehand, though, and bounce some ideas internally.

**Comment by rtwell** [comment]
thanks for handling all the emaily stuffs, @cmc333333

**Comment by cmc333333** [comment]
Based on feedback, we'll now be holding a spitballing session internally.

**Comment by cmc333333** [comment]
We held this session internally and approached potential solutions from four starting points:
* we're trying to showcase particular text
* we're trying to tie in forms
* we're trying to tie together OMB metrics
* we're trying to highlight "states of mind" like general preference

Ideas shared included
* greying out/defocusing non-requirement text; displaying _only_ requirement text
* allowing only one chunk of text to be highlighted at a time
* reduce the amount of highlight (e.g. only indicating the beginning of a requirement or near words like "shall"/"must")
* creating checklists of specific tasks (though note a significant problem of overlapping tasks between documents)
* allow users to highlight anything, track it per user
* take user-provided highlights, display the most frequent (as on Medium)
* Q&A site / forum (though note potential for misinformation here). Potentially moderated by OMB lawyers. We'd expect a forum per memo.

One of the bigger take aways, though is that we should think through a toggle to toggle on some or all requirements and see if users activate it.
