### ISSUE TITLE
visual tweaks to M-16-19

### ISSUE THREAD

**Issue by rtwell** [18F/omb-eregs#718]
## Random visual tweaks 

- [x] 1) The footnotes appear to be altering the line height 
- [ ] 2) let's kill the gold in the H4s and change to black 
- [ ] 3) for numbered lists, let's simplify and use sans-serif for the numbers as well. I thought it looked easier to read with the sans in there for numbers, but the difference in the base-size of the fonts is throwing the alignment off. 
- [ ] 4) The spacing between the headers and body copy should be adjusted:
### live site
![image](https://user-images.githubusercontent.com/12564977/33456966-a4e8980c-d5e6-11e7-8143-d714d0e86a83.png)
### no markup
![image](https://user-images.githubusercontent.com/12564977/33457287-a36b35a6-d5e7-11e7-94d5-54e54c1d508c.png)
### markup
![image](https://user-images.githubusercontent.com/12564977/33457463-2ecde7ec-d5e8-11e7-9599-7fd4ba178a69.png)

**Comment by cmc333333** [comment]
Heads up that #712 should resolve 1 (and perhaps 4).

**Comment by cmc333333** [comment]
Resolved by #786
