### ISSUE TITLE
Move omb-pdf into omb-eregs

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/omb-eregs#721]
Currently it's a separate codebase, but if we're going to use it we should probably move it into the `omb-eregs` repository.

**Comment by toolness** [comment]
The codebase itself was brought here in #755, but it's just a useless appendage at the moment: we still need to hook it up to CI, linting, have it be usable by the API app, and all that good stuff.

**Comment by yowill** [comment]
Done!
