### ISSUE TITLE
Synthesize research for MVP features list

### ISSUE THREAD

**Issue by austinhernandez** [18F/omb-eregs#727]
- [x] Complete initial round of interviews
- [x] Synthesize data with development team
- [x] Agree on MVP

**Comment by austinhernandez** [comment]
[MVP feature list doc](https://docs.google.com/a/gsa.gov/document/d/1rRkCMb4oMdaB7dNlBQgTQ9ylFwqf72S_iDyUWqIqMTc/edit?usp=sharing)
[Mural for synthesizing](https://app.mural.ly/t/gsa6/m/gsa6/1512417474467/08893a3aad36c949da6153c8f0846ad243601e69)

**Comment by carodew** [comment]
Given that we've written all the epics and some of the user stories (for the ones we'll work on first) I think we can call this card done – but I'll wait until @austinhernandez is back so he can confirm.
