### ISSUE TITLE
Design: Next steps for Search 

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#778]
Goal: 
Being able to search across all documents with what's in the documents

AC:
- Search the entire document, not just the requirement 
- Search across all documents
- Filtering (bonus if possible)

**Comment by carodew** [comment]
Each bullet is it's own issue, there's (at least) three different user stories going on here. 

The first bullet point is already captured in #693. I'll break apart the other two. 

I'm working six days this sprint (assuming I continue feeling better) so unlikely I'll be able to complete all the things assigned to me, so I'll do my best to prioritize.

**Comment by carodew** [comment]
So this is now 
- #790: search for documents by document title or number
- #791: filter search results (which still needs to be better defined) 

in addition to 

- #693: search within document 

Given the push to add more policy docs to the library, is it safe to assume that #790 is the highest priority?  cc @yowill

**Comment by carodew** [comment]
also recommending that we close this issue
