### ISSUE TITLE
Placeholder: Minimal interface

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#79]
Matt noted that if we had a minimal interface for searching and filtering by keyword, he'd be able to get folks to start using the system for everyday work.

TODO: decompose this during sprint planning

**Comment by theresaanna** [comment]
A first step could be to combine what is there between the /keywords and /requirements pages onto one page.

**Comment by cmc333333** [comment]
@theresaanna agreed -- I think that most matches #88.

This ticket's been expanded into #87, #88, #89, #90
