### ISSUE TITLE
As an agency implementor, I want to search for a specific policy by policy title, number, and policy text, so that I can find a document that I'm already familiar with. 

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#790]
## ac 
- [ ] design for no search results
- [ ] users who know exactly what document they want can jump directly to that document (skipping search results page)
- [ ] some other stuff

**Comment by carodew** [comment]
Notes – 

There are a few different use cases here: 

1. I know the policy I'm looking for (by either title or document number), and I want to find it via search. 

2. I don't know what policy I'm looking for, but I know there is a policy about [subject], and I want to search for it via keywords/phrase related to that [subject]. For example, I know there is a policy about external links on a government website, but I can't remember what that policy is called or when it was issued, and I certainly don't know if a newer policy came out that is supersedes the policy that I vaguely remember reading or hearing about. So I'll do a search for "external links" because I remember that phrase in the policy. I'm probably familiar with words and phrases common to the domain. So if I'm looking for stuff about data centers, I might search for "virtualization" because I know that's a thing (regardless of whether or not I remember seeing that word in the policy). 

3. I don't know if there is a policy about [subject] but I'm being asked to do something in that space and I'm going to search for it. I'm not going to know what keywords or phrases are contained within the policy document, and I'm probably not super familiar with the specific words or phrases common to the domain. 

The first use case above is pretty easy to solve for and probably applies to many of our users, but I wouldn't discount 2-3. Make things easier for folks who are the hardest to serve and you make things easier for everyone.

**Comment by carodew** [comment]
![9efcb857-4ba9-42c6-83c9-2d85a4a4155b](https://user-images.githubusercontent.com/10144074/34172665-d12360e4-e4c0-11e7-88a7-3209b90e1ecb.png)

If I know the policy number or policy title, then perhaps I should be presented with the option to hop straight to the policy via an autosuggest menu. Skips the step of finding a policy in the list. 

Will still need a list view in case the autosuggest doesn’t pull up the one I’m thinking of and for text search.

**Comment by carodew** [comment]
![2570dcab-792f-48f6-8e09-1034cfdbcf88](https://user-images.githubusercontent.com/10144074/34173647-29681b0c-e4c4-11e7-876b-dc35db130204.png)

Here is a flow related to the first one but the user isn’t entirely sure what the policy number or title is. Instead the user types in what they know and then scan the search results to find the policy they’re looking for. 

Similar flow to the first but with a brief interlude on the search results screen.

**Comment by carodew** [comment]
![4b184a59-f283-4a0b-ab16-da683ecde970](https://user-images.githubusercontent.com/10144074/34176874-7ebe7ee2-e4cf-11e7-8300-027b8d9c39a9.png)

In this last flow, the user doesn’t know which policy to look for,  but knows a topic/keyword. so the user searches for that, ends up clicking on the first result, finds the paragraph that proves her point, and shares it with her colleague.

**Comment by carodew** [comment]
Closely related to this is #792 – which is about finding a policy using a popular search engine. 

We know users do this, in part because this is a standard way of finding anything online, and also because they don't trust the links on government websites (since so many of them 404). We also know from research that users will look at the URLs/sources in the search results from a popular search engine to try to pick the most authoritative one.

**Comment by carodew** [comment]
Adding a previous task flow analysis – 

![Search by keyword-task-flow-analysis.png](https://images.zenhubusercontent.com/5a1349588a75884b90883076/2971c5b7-163d-40eb-a4ba-c324f740e983)

**Comment by carodew** [comment]
## design considerations

- [ ] search with no results (just need to design this page)
- [ ] topic search when the topic word doesn't appear in the text
- [ ] default sort order? How are we calculating relevancy? How is that different from most recent? 
  - weight keywords more if they show up in a policy title
  - weight number of appearances within the document
  - weight recency of policy issuance
- [ ] how many words before/after search term in snippet?

**Comment by rtwell** [comment]
## Search with no results
This is a first pass / my thinking on how we might help folks find stuff or get them on the path to finding what they searched. 
![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/3831167e-7245-4c47-8a0a-9c1167945978)

**Comment by rtwell** [comment]
## Search suggestions
![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/8d4b6cba-a09f-437a-9cb6-8fadfe6f6733)

**Comment by rtwell** [comment]
## Full search results
![OMB-Search results.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/60e0108d-dd30-41a7-b197-f7173fdb090f)

**Comment by carodew** [comment]
so good.
