### ISSUE TITLE
Solidify ATO requirement around SSO

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#80]
Based on the briefest of conversations, it sounds like we'll want to implement max.gov.

* Check if this is an acceptable solution w/ OMB
* Chat with @kaitlin about admin-side max implementation (it's used in https://github.com/fedspendingtransparency/data-act-broker-backend)

**Comment by kaitlin** [comment]
Happy to chat -- one thing you'll need is an IAA with them (which can take some time), although data.gov already has one I believe which makes any subdomain of *.data.gov "Just Work".

**Comment by cmc333333** [comment]
We'll be using max.gov, but need to kick off that process (will be a new ticket). Kaitlin pointed us to:
* A description of the service: https://community.max.gov/pages/viewpage.action?pageId=110657589
* Form to start the process: https://community.max.gov/pages/viewpage.action?pageId=550372346
* Example code: https://github.com/fedspendingtransparency/data-act-broker-backend/tree/development/dataactbroker
