### ISSUE TITLE
Hold React review

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#81]
With an expert from outside the team.

**Comment by yowill** [comment]
contingent on #53

**Comment by cmc333333** [comment]
I'm going to push this to next sprint as we're still getting essential stuff like fonts, scss libraries, etc. figured out.

**Comment by cmc333333** [comment]
@adborden's feedback: https://docs.google.com/document/d/18YjPmGdXfSdHfGXd36WUYGenXryEekYGD80kxs9zZfU/edit

**Comment by cmc333333** [comment]
@jeremiak's feedback:

* Surprised that we didn't need a separate state manager (like redux). Jeremia adds redux by default
* Autocomplete component shouldn't be Pure since it has state
* Server-side autocomplete uses the word "Add"; differs from enhanced JS
* There are security concerns with JSON.stringify for large objects. See http://redux.js.org/docs/recipes/ServerRendering.html#security-considerations
* Rename endpoints/router.jsx to something else. isomorphic-render? server-render? html.js?
* Docker setup was easy
* Look into the "Relay" library to replace resolver: https://facebook.github.io/relay/  (?)
* "ui" may not be a great name
* .jsx files should be largely component. Try to split out js files.
* React-router is a-ok
    * doesn't necessarily play well with redux, though.
    * not a fan of react-router-redux; FBI just sets redux state on route change
* React context is generally a no-no, but might make sense for passing around the router/location info
* Can use router callbacks to trigger Google Analytics if it doesn't work out of the box for push state changes.

**Comment by cmc333333** [comment]
Thanks again @aborden and @jeremiak!
