### ISSUE TITLE
Admin editor development style work

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#818]
- [x] Take the baked in Django admin editor and make it work using Ryan's styles

**Comment by cmc333333** [comment]
There are several steps necessary to implement this; I think the first few are:
* We currently use [django-admin-interface](https://github.com/fabiocaccamo/django-admin-interface) to swap out our (USWDS) color scheme. We should play around with its configuration (not on in the admin section currently) to see how far that'll get us
* For custom css, we'll want to add a new entry in the api/admin's [webpack](https://github.com/18F/omb-eregs/blob/6760565f9f29d4cd954d62a28ca64eff13d46de1/api/webpack.config.js)
* We'll probably need to modify the Django admin base template to include that css and add a left-hand menu. Consider [django-overextends](https://github.com/stephenmcd/django-overextends) to prevent a lot of copy-pasta

**Comment by cmc333333** [comment]
@rememberlenny do you want to tackle the django-admin-interface exploration? Ideally we could configure it with our color scheme as a safe base, then add custom styles on top. To get started, you'll need to activate that app in the admin:
```patch
diff --git a/api/ereqs_admin/admin.py b/api/ereqs_admin/admin.py
index d3456da..0d82bfb 100644
--- a/api/ereqs_admin/admin.py
+++ b/api/ereqs_admin/admin.py
@@ -1,3 +1,5 @@
+from admin_interface.admin import ThemeAdmin
+from admin_interface.models import Theme
 from django.conf import settings
 from django.contrib.admin import AdminSite
 from django.contrib.auth.admin import GroupAdmin, UserAdmin
@@ -51,6 +53,7 @@ admin_site.register(Office, OfficeAdmin)
 admin_site.register(Policy, PolicyAdmin)
 admin_site.register(Requirement, RequirementAdmin)
 admin_site.register(Topic, TopicAdmin)
+admin_site.register(Theme, ThemeAdmin)

 if settings.MAX_URL:
     admin_site.register(User, PasswordlessUserAdmin)
```

If you get to a point where things are looking about right, we can add a new data migration to set it permanently. It'd be very similar to the [first migration](https://github.com/18F/omb-eregs/blob/4deefea826531e3df07a6e254c74e3736fc83fdc/api/ereqs_admin/migrations/0001_initial.py) save we'd be updating rather than creating.

**Comment by cmc333333** [comment]
The InVision prototype: https://gsa.invisionapp.com/share/NXEJ61FDE#/screens/271363956

**Comment by austinhernandez** [comment]
Please use the styles that @rtwell developed for the front-facing UI. They should be the building blocks for colors, fonts, spacing etc. Then you will use the styles for the admin editor for components that aren't available on the front-facing UI, which is here [here on InVision](
https://gsa.invisionapp.com/d/main/#/projects/prototypes/12532570/assets).

We would love to start adding to a OMB [component library](https://standards.usa.gov/components/form-controls/) so it's scalable and consistent.

**Comment by cmc333333** [comment]
We changed the default theme and added a foundation for sharing styles between the UI, editor, and admin this sprint, but didn't get much further. I'd break down the remaining steps as:

* Carry over fonts from the UI to the admin (depends on #890)
* Carry over fonts from the UI to the editor (depends on #890)
* Style left-side navigation bar; reactivate it (deactivated in #880)
* Style input elements to match designs (specifically, font size/padding/etc.)
* Stack input elements so the label is above the input (@rtwell's major ask of the Django admin) if possible. Be sure to check if there's a Django admin config that'll move this along quicker than overriding CSS
* Work with @rtwell and @austinhernandez to rustle up remaining issues; create issues for them.
