### ISSUE TITLE
Productionalize Prose Mirror work

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#820]
#798 is the non-productionalized version.

**Comment by cmc333333** [comment]
Proposed breakup (we can make issues if desired):
* server side write (we’ll need to also pay attention to permissions here). As @toolness noted, this doesn’t have too many dependencies
* set up prose mirror build process, say on a static page (similar to the demo). Goal would be technical mechanics; we could use the example schema
* add our schema; we can likely split this up by node type
* functions for loading data from the API
* functions for writing data from prose
* integrating this with the admin

**Comment by cmc333333** [comment]
We finished server-side write, setting up prose mirror, loading data, and part of our schema.

Remaining tasks
* Writing data from the ProseMirror editor to the API (I'm working on this now)
* Adding schema/display for remaining content types (or decide to punt to the advanced editor)
    * Preamble (has multiple sub types) - we hid this in Atul's prototype
    * Lists & List items
    * Footnotes
    * Tables (and their components)
    * Math
* Adding schema/display for remaining inlines (or decide to punt to the advanced editor)
    * Footnote citations
    * External links
* Add a link or similar mechanism to reach the editor from the admin

**Comment by yowill** [comment]
Broken out into more granular tasks https://github.com/18F/omb-eregs/issues/944 https://github.com/18F/omb-eregs/issues/922 https://github.com/18F/omb-eregs/issues/943 https://github.com/18F/omb-eregs/issues/941 https://github.com/18F/omb-eregs/issues/942 https://github.com/18F/omb-eregs/issues/940
