### ISSUE TITLE
Update our Style guide

### ISSUE THREAD

**Issue by rtwell** [18F/omb-eregs#825]
A while ago, @toolness made a quick style guide page with some basic elements we're using. Now that the editor is coming to life, @austinhernandez and I thought we should consolidate our styles and update that page so design and dev have a single source for all the things!

Our plan of attack:

1) @rtwell will gather all the styles that are used (or will be) on the main site
2) @austinhernandez will gather all the components / styles used on the editor (barring what Django lets us change)
3) smash them into one styleguide

## actions 
- [ ] design review from @rtwell 
- [ ] handoff to devs

**Comment by austinhernandez** [comment]
- [Download the Sketch file](https://invis.io/a/7A1CAH4ZM4KVQ9)
- [View a static PNG here](https://gsa.invisionapp.com/share/NXEJ61FDE#/272841277_OMB_Styles)

**Comment by austinhernandez** [comment]
hey @xtine 

Thanks for our overview call: Here is our Sketch file on [Google Drive v1](https://drive.google.com/file/d/1xSZ54tgqt1iFMQMZvV0YJLzks9FzPurH/view?usp=sharing)

This is @rtwell and my first draft of style guide. They are split in two artboards with admin and front-end policy library view. Everything is a work in progress and TBD!

**Comment by yowill** [comment]
Finished enough for now!
