### ISSUE TITLE
Configure django-admin-interface to match our color scheme

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#845]
Our Django admin has a layer of styling via [django-admin-interface](https://github.com/fabiocaccamo/django-admin-interface). This won't let us change _all_ of the things (we'll need to add some new style rules), but it does give us a hook into replacing a healthy chunk of the admin theme. Changing the theme through this interface will give us a bit more confidence that we've covered Django's full ui. 

Configure that to match the color scheme in our mockups, using only colors from our palette. When we don't have a necessary color, powwow with @rtwell and @austinhernandez to see if it should be added.

Once this is configured, we'll need to export it into the database via a data migration so that it makes its way to all our sites.

This is part of #818

**Comment by yowill** [comment]
Finished and demoed!
