### ISSUE TITLE
Interaction and visual design – import a PDF from desktop

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#846]
Design work for #828 

## acceptance criteria 
- [ ] User can select a single policy document (PDF) from their computer import (multi-select or bulk import can come later)
- [ ] The select function indicates which files can and can't be selected
- [ ] User receives feedback that the system is working on importing the document when there's a lag between hitting "upload" and the upload completing.
- [ ] User receives feedback on whether the import was successful or unsuccessful
imported text is saved within the database
- [ ] policy text is labeled with the proper workflow phase tag

## actions 
- [ ] create task flow diagram and identify potential error states
- [ ] create wireframes and identify keyboard tab order
- [ ] write UI copy, error messages
- [ ] create visual design mock ups 

## outstanding questions 
- [ ] How do we prioritize mobile interactions for the admin side?

**Comment by yowill** [comment]
Broken out into single vs bulk import tickets https://github.com/18F/omb-eregs/issues/997 https://github.com/18F/omb-eregs/issues/995 https://github.com/18F/omb-eregs/issues/996
