### ISSUE TITLE
Interaction design: enter/edit the preamble and metadata of a document. 

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#849]
## assumptions 
- [ ] user has already uploaded the pdf and the importer has chewed on it, and spit out what it thinks the content is. 

## actions 
- [x] create wireframes, identify keyboard tab order
- [x] document necessary error messages for invalid entries

**Comment by carodew** [comment]
Notes from demo 1/19/18 – not sure if checkbox is necessary or if the field should just be optional. We should probably define what benefit we think the checkbox "required if present" interaction pattern offers, and if it's not much perhaps a simpler approach is better.

**Comment by austinhernandez** [comment]
![check your formattingv3](https://user-images.githubusercontent.com/23194720/35756481-8577c04e-0839-11e8-8cb6-414d327092d6.png)

## Title
### Instruction about what to do on the page.
### Text fields and keyboard tab orders:
1. Title [field is 2x as long as other fields]
2. Policy number 
3. This policy does not have a number [checkbox]
4. Issuance date [accessible calendar popup on click/tab]
5. Sunset date (optional) [accessible calendar popup on click/tab]
6. Public checkbox [I saw this on the demo but not sure what it's use is. ]

## Error States
![check your formattingv3error](https://user-images.githubusercontent.com/23194720/35756746-6670e04e-083a-11e8-8b70-42a20132a09b.png)

## Important notes

- Error messages appear where helper text does and lets the user know what they did wrong. 
- All the text needs to go through @thebestsophist.
- Document text on next page _temporarily_, only until it is able to be embedded on the same page.

**Comment by thebestsophist** [comment]
Mapped out more of content model in #966, now have a decent grasp of what each fields are doing (still a number of unclear ones, but much better picture now), will be able to edit and clarify error+description text in UI.

**Comment by rtwell** [comment]
@thebestsophist @austinhernandez @cmc333333 do we need a "this title is already being used" error state?

**Comment by cmc333333** [comment]
@rtwell Seems important. Same should probably go for the policy number.

**Comment by austinhernandez** [comment]
- [ ] We need to update this basic flow with errors to show:
- [ ] Example of error then list out the errors (duplicate title, wrong date)
- [ ] Add workflow dropdown that shows unpublish (KISS, no extra things)
- [ ] Mess around w/ to include the status of yr document (e.g. published, in review, etc.). can be a button, changeable thing, update button.
- [ ] Unpublish work flow
- [ ] What the empty page looks like on the front-end policy library view (AKA under construction gif)

TO BE SPLIT UP IN DIFFERENT TICKETS PROBABLY

**Comment by rtwell** [comment]
this was tackled here: https://github.com/18F/omb-eregs/issues/1010
