### ISSUE TITLE
Content design – research what 'preamble' information we need to support

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#852]
Most policy documents have meta information (such as title, policy number, issue date, issuing authority, etc) at the beginning of the document, but we know that different kinds of documents have different kinds of information here. 

For example, M-16-19 has a policy number, a "memoranda to" field, policy title, issue date, issuing authority, and a link to the PDF. However, we know that not all policy and guidance documents follow this template. We'd like to get a good sense of what the most common data elements are that we'll need to support on a first pass (knowing that we can go back in later if we come across a document with a preamble surprise).

## AC
-  [ ] Identify preamble information from a representative sample of types of documents the policy library will support
- [ ] For each element, identify formatting/etc that we'd need to support (e.g. special characters, date format, etc)
- [ ] Identify which elements should be optional, required, or required if present

## related stories
Results from this research will inform #831. This is broader in scope than #855, which only compares M-16-19 with the current admin interface.

**Comment by austinhernandez** [comment]
Here is the preamble information as it stands right now on CRUFT. I assumed the gray input field labels meant that this information was not necessary, but I may be wrong. @cmc333333 mentioned it might be necessary to sort and categorize. 

* Policy number [mandatory]
* Title  [mandatory]
* Uri (I assume this is URL) [mandatory]
* Omb policy id
* Policy type
  * None
  * Circular
  * Executive
  * Guidance
  * HSPD
  * Law
  * Memoranda
  * National Action Plan
  * Plan
  * PPD
  * Policy Review
  * Standards
  * Strategy 
* Slug [mandatory]
* Issuance [mandatory]
* Sunset
* Policy Status
- Document Source
- Public (this is a checkbox)
- Issuing body [mandatory]
- Managing offices

![cruftpreamble](https://user-images.githubusercontent.com/23194720/34891983-8c02b1b6-f7a5-11e7-990f-18795fda5606.png)

**Comment by carodew** [comment]
Issuing body – this is slightly different from how we're thinking about the "from" field in the preamble information. Currently this is treated more like metadata. 

Public – that won't be considered 'preamble' information, but will be handled completely differently in the UI.

Managing office –  I think is not in our new MVP roadmap.

**Comment by carodew** [comment]
I did some more digging and I think for right now this is unnecessarily duplicative of #855 – most memos have the same preamble information and it makes more sense to put this off until we more explicitly expand to other document types.
