### ISSUE TITLE
As Cordelia, I want to have access to the systems I need and understand enough about the background of the project, so I can start working on content design.

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#862]
## ac 
- [x] all the systems that Cordelia needs access to to do work are identified
- [x] she has the right amount of access to them
- [ ] After reviewing the documentation we send her and answer whatever questions she has, Cordelia reports that she understands enough about the project to get started comfortably and confidently

**Comment by carodew** [comment]
First step is adding @thebestsophist to the GitHub repo so we can co-assign her to this issue.

**Comment by carodew** [comment]
Systems @thebestsophist needs access to 
- [ ] this GitHub repo
- [ ] Zenhub
- [ ] Invision
- [ ] UX files on Google Drive (everything else is accessible to everyone at 18F already, some UX files are only shared with the project team because they contain PII)
- [ ] Mural
- [ ] what else?

**Comment by thebestsophist** [comment]
all done!

**Comment by yowill** [comment]
Next steps for the content audit here: https://github.com/18F/omb-eregs/issues/897
