### ISSUE TITLE
Running individual tests that modify Django's URLconf explode

### ISSUE THREAD

**Issue by toolness** [18F/omb-eregs#863]
I noticed when working on just the `document` package today that running `pytest document/` fails on `document.tests.views_test.test_editor_works` with an _extremely_ long error log culminating in the following:

```
django.urls.exceptions.NoReverseMatch: 'admin' is not a registered namespace
```

However, running `pytest` by itself, without any arguments, works fine.

After some sleuthing I realized this is due to #854, which added the following top-level code in a template tag module:

```python
menu_archetype = MenuItem.new('', children=(
    MenuItem.new('Policies', children=(
        MenuItem.new('View all policies',
                     url=reverse('admin:reqs_policy_changelist')),
        MenuItem.new('Add new', url=reverse('admin:reqs_policy_add')),
    )),
    MenuItem.new('Users', url=reverse('admin:auth_user_changelist')),
    # Settings depends on the user id, so is added later
))
```

The culprit is the use of `reverse()` on an admin URL.  Because `test_editor_works` changes Django's URLconf to `document.urls`, which doesn't include the admin package, `admin` is no longer a valid URL namespace at the time that Django initializes itself, which is when it loads all the templatetags.  Commenting out the above code fixes the problem.

I think one solution to this might be to make `menu_archetype` a lazily-instantiated module-level variable, so it starts out at `None` and only acquires its actual value the first time its template tag is used.  What do you think @cmc333333 ?

**Comment by cmc333333** [comment]
That's rather annoying. If we're going to build that menu lazily, would it make more sense to just instantiate within `nav_menu`? That'd also remove a lot of the benefit of the two-phase create-menu-then-activate, so it'd probably make sense to rewrite that, too.
