### ISSUE TITLE
Akoma Ntoso renderer may not render href of external_link

### ISSUE THREAD

**Issue by toolness** [18F/omb-eregs#867]
I'm not very familiar with Akoma Ntoso, but this is how it renders external links:

```xml
<content>OMB Memorandum M-15-14, “<external_link>Management and Oversight of Federal Information Technology</external_link>,” June 10, 2015.</content>
```

As far as I can tell, there is no `href` attribute (or semantic equivalent) that indicates where the highlighted text should actually go.

**Comment by cmc333333** [comment]
[Looks like](https://github.com/18F/omb-eregs/blob/b3076801d2c7fc4ce3440c27af667781ddcfcea4/api/document/renderers.py#L39) I forgot to add these attributes. I bet we can start by adding all string attrs without deeper inspection; footnote citations will be a bit more challenging.
