### ISSUE TITLE
Interaction and visual design: admin side list of all documents

### ISSUE THREAD

**Issue by carodew** [18F/omb-eregs#888]
## actions 

- [ ] create task flow diagram, identify keyboard tab flow
- [ ] visual design mock ups or direction
- [ ] Check with devs to see what kind of sorting/filtering we can get out of the box.

## ac
- [ ] include default sort order by release date of document
- [ ] filter by workflow status

**Comment by carodew** [comment]
[Research plan / conversation guide](https://docs.google.com/document/d/1b5zUjEoarQlMxbVhnkrZZjbuMLGDlzLUn9ut1uBWdnk/edit) (Note – this file is only available to 18F project team members. I can't share it publicly, so please don't ask).

**Comment by yowill** [comment]
Closed for broken out tickets https://github.com/18F/omb-eregs/issues/1008
