### ISSUE TITLE
Consider using the HTML5 document outline instead of h1-h6

### ISSUE THREAD

**Issue by toolness** [18F/omb-eregs#896]
This is a question @cmc333333 just asked in https://github.com/18F/omb-eregs/pull/883#discussion_r162946504 that might be revisited in the future, so I thought it best to file a separate issue, just so it's super-visible going forward.

To provide some context, in the original ProseMirror prototype I wrote in #798, I used the [HTML5 Outline Algorithm](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines) to create `<section>` elements with only `<h1>`s in them, relying on the outline algorithm to communicate the heading levels according to their level of nesting (after some research today, it looks like there is actually a brand new `<heading>` element I could have been using instead).  This is distinct from HTML's standard "flat" system of not relying on nesting and only using `<h1>` through `<h6>`.

That said, all signs point to **no** when it comes to using this in production. According to [The Document Outline Dilemma (2017)](https://css-tricks.com/document-outline-dilemma/) the big problem lies in the way that browsers expose the document outline to accessible technologies like screen readers:

> Browsers modified their default styles so that headings inside of nested sections would have progressively smaller font sizes (just like how the default style for `<h3>` has smaller font than `<h2>`, which is smaller than `<h1>`). But they didn't change the way they exposed heading levels to the accessibility APIs that are used by screen readers. And screen-reader users are the only ones who really experience heading levels as part of the user interface. 

So, we should probably steer clear of it--even though everything might _look_ fine in all the browsers we use, it will almost certainly massively degrade the experience for users of ATs!

So I just recommend closing this issue, basically. And maybe re-opening it if the situation ever gets better (which doesn't seem very likely).

**Comment by cmc333333** [comment]
:(

Thoughtful analysis, @toolness, thank you. I agree we can close.
