### ISSUE TITLE
Cordelia documentation audit plan 

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#897]
AC:
- [ ] Review documentation for the project to get fully up to speed
- [ ] Create an audit plan (and post in comments)

**Comment by thebestsophist** [comment]
To do:
- [] Content model+description
- [] Site information architecture map (as is)
- [] Scope out plan for mapping editorial workflow
- [] Plain-language summary of records retention and archival policies that affect this project?
- [] Beginners guide to Akoma Ntoso #931

**Comment by thebestsophist** [comment]
Breaking into more detailed tasks to finish in next sprint.
