### ISSUE TITLE
Design editor functionality for adding content types

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#902]
The prototype editor @toolness built worked really well for editing existing text, but didn't allow users to create *new* content (aside from paragraphs). We need to design a UI (buttons, keyboard combinations, etc.) for adding:

## Blocks
* Paragraphs
* Headings (/Sections - assuming these are related; account for Table of Contents depth)
* Lists
    * We also need a way to set/modify list item "markers" like `a.`, `(2)`, `●`, etc.
    * List items can also have "titles" separate from their text content
* Footnotes (presumably, connected to citations)
* Tables, Math (I'm betting we're punting on these for now)

## Inlines
* External links
* Footnote citations
* Inline requirements (I assume this can be punted, too)

**Comment by carodew** [comment]
@cmc333333 let's coordinate on creating design issues – I already have this as #832 and multiple overlapping issues is just confusing. Also the design team needs to be able to actively participate in creating and deciding on their workflow.

**Comment by cmc333333** [comment]
Cool. Happy to move all the content to that issue and close if that's better. Your call @austinhernandez
