### ISSUE TITLE
Serializer level validation for schema 

### ISSUE THREAD

**Issue by yowill** [18F/omb-eregs#906]
**Serializer level AC:**
- [ ] Check that DocNode fields are validated (required, character limits, etc.)
- [ ] Check that Inline/Annotation/Content fields are validated (required, character limits, etc.)
- [ ] Check if there are any input fields which aren't class-level, declarative, DRF Field classes. If so, we'll need to validate them, too.

**Comment by cmc333333** [comment]
I think @toolness covered this in his validations last sprint.

**Comment by toolness** [comment]
Ah yeah, this was resolved by PRs like #937, #949, #959, and #961, I think.
