### ISSUE TITLE
Design editor functionality around saving documents

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#909]
We've been building editor functionality which asynchronously saves the document when the user pressed `Cmd-s`. As @toolness [points out](https://github.com/18F/omb-eregs/issues/822#issuecomment-359485583), this doesn't work like the rest of the Django admin, which does full page refreshes and has a "Save" button at the bottom.

Like #902, we have lots of options for how to implement this; we'll need to start with a design.

**Comment by toolness** [comment]
Oh, I should also note that the <kbd>Cmd</kbd>+<kbd>S</kbd> functionality is also just a quick hack to make saving _possible_, rather than making it particularly user-friendly, so we can e.g. replace it with auto-saving or whatever else is most humane for our peeps.

**Comment by yowill** [comment]
Finished as a save button, further work will be continued in: https://github.com/18F/omb-eregs/issues/911
