### ISSUE TITLE
API function to order results by policy

### ISSUE THREAD

**Issue by cmc333333** [18F/omb-eregs#96]
We want to be able to prototype something like
![](https://cloud.githubusercontent.com/assets/4267825/23070787/3ebd9370-f4fa-11e6-99da-3c7e8cce5bda.png)
(from #29), so we need the API to return results in a different order. For now, I don't think we should worry much about the order of the policies -- let's just return in policy id order.

Something which seems likely to help here: http://www.django-rest-framework.org/api-guide/filtering/#orderingfilter (iirc, this is partially implemented now)

**Comment by tadhg-ohiggins** [comment]
Addressed by <https://github.com/18F/omb-eregs/pull/119>.
